-- Initial Source Directory import for My Seed Vault autocomplete.
-- Idempotent: rows are upserted by the generated public.source_directory.normalized_name.

with seed_rows(name, aliases, source_type, country, verified, active) as (
  values
    ('Private Breeder', array[]::text[], 'fallback', null, false, true),
    ('Friend / Trade', array['Friend Trade']::text[], 'fallback', null, false, true),
    ('Self Produced', array['Home Produced']::text[], 'fallback', null, false, true),
    ('Unknown Source', array['Unknown']::text[], 'fallback', null, false, true),
    ('Other', array[]::text[], 'fallback', null, false, true),
    ('Wizard Trees Genetics', array['Wizard Trees']::text[], 'boutique_breeder', 'United States', true, true),
    ('DNA Genetics', array['DNA']::text[], 'breeder', 'United States', true, true),
    ('Reserva Privada', array[]::text[], 'legacy_genetics', 'United States', true, true),
    ('Crockett Family Farms', array['Crockett Family']::text[], 'breeder', 'United States', true, true),
    ('Archive Seed Bank', array['Archive Seeds']::text[], 'breeder', 'United States', true, true),
    ('Exotic Genetix', array['Exotic Genetics']::text[], 'breeder', 'United States', true, true),
    ('Ethos Genetics', array['Ethos']::text[], 'breeder', 'United States', true, true),
    ('In House Genetics', array['IHG']::text[], 'boutique_breeder', 'United States', true, true),
    ('Solfire Gardens', array['Solfire']::text[], 'boutique_breeder', 'United States', true, true),
    ('Compound Genetics', array['Compound']::text[], 'boutique_breeder', 'United States', true, true),
    ('Tiki Madman', array['Tiki Madman Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Bloom Seed Co', array['Bloom Seed Company']::text[], 'boutique_breeder', 'United States', true, true),
    ('Capulator', array['Capulator Seeds']::text[], 'boutique_breeder', 'United States', true, true),
    ('Seed Junky Genetics', array['Seed Junky']::text[], 'boutique_breeder', 'United States', true, true),
    ('Jungle Boys', array['Jungle Boys Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Cookies Seed Bank', array['Cookies Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Grandiflora Genetics', array['Grandiflora']::text[], 'boutique_breeder', 'United States', true, true),
    ('Berner Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Karma Genetics', array['Karma']::text[], 'breeder', 'Netherlands', true, true),
    ('Lit Farms', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Cannarado Genetics', array['Cannarado']::text[], 'boutique_breeder', 'United States', true, true),
    ('Relentless Genetics', array['Relentless']::text[], 'boutique_breeder', 'United States', true, true),
    ('Bodhi Seeds', array['Bodhi']::text[], 'legacy_genetics', 'United States', true, true),
    ('Masonic Seed Co', array['Masonic Seeds']::text[], 'boutique_breeder', 'United States', true, true),
    ('The Cali Connection', array['Cali Connection']::text[], 'breeder', 'United States', true, true),
    ('CSI Humboldt', array['C.S.I. Humboldt']::text[], 'breeder', 'United States', true, true),
    ('Humboldt Seed Company', array['HSC']::text[], 'breeder', 'United States', true, true),
    ('Humboldt Seed Organization', array['HSO']::text[], 'legacy_genetics', 'Spain', true, true),
    ('Humboldt CSI', array[]::text[], 'breeder', 'United States', true, true),
    ('Mendo Dope Seeds', array['Mendo Dope']::text[], 'breeder', 'United States', true, true),
    ('Mean Gene From Mendocino', array['Mean Gene']::text[], 'legacy_genetics', 'United States', true, true),
    ('Freeborn Selections', array['Freeborn']::text[], 'breeder', 'United States', true, true),
    ('Twenty20 Mendocino', array['Twenty20']::text[], 'breeder', 'United States', true, true),
    ('NorCal Genetics', array[]::text[], 'breeder', 'United States', true, true),
    ('NorStar Genetics', array['NorStar']::text[], 'breeder', 'United States', true, true),
    ('808 Genetics', array[]::text[], 'breeder', 'United States', true, true),
    ('707 Seed Bank', array['707 Seeds']::text[], 'breeder', 'United States', true, true),
    ('3rd Coast Genetics', array['Third Coast Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Aficionado Seed Bank', array['Aficionado Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Alphakronik Genes', array['Alphakronik']::text[], 'legacy_genetics', 'United States', true, true),
    ('Annunaki Genetics', array['Annunaki']::text[], 'breeder', 'United States', true, true),
    ('Apothecary Genetics', array['Apothecary']::text[], 'legacy_genetics', 'United States', true, true),
    ('Badgers Dank Seeds', array['Badgers Dank']::text[], 'boutique_breeder', 'United States', true, true),
    ('Barrel Proof Genetics', array['Barrel Proof']::text[], 'boutique_breeder', 'United States', true, true),
    ('Boneyard Seeds NorCal', array['Boneyard Seeds']::text[], 'boutique_breeder', 'United States', true, true),
    ('Boston Roots Seed Co', array['Boston Roots']::text[], 'boutique_breeder', 'United States', true, true),
    ('Brothers Grimm Seeds', array['Brothers Grimm']::text[], 'legacy_genetics', 'United States', true, true),
    ('CannaVenture Seeds', array['CannaVenture']::text[], 'legacy_genetics', 'United States', true, true),
    ('Chemdog Seeds', array['Chemdog']::text[], 'legacy_genetics', 'United States', true, true),
    ('Coastal Seed Company', array['Coastal Seeds']::text[], 'legacy_genetics', 'United States', true, true),
    ('Covert Genetics', array['Covert']::text[], 'boutique_breeder', 'United States', true, true),
    ('Crane City Cannabis', array['Crane City']::text[], 'boutique_breeder', 'United States', true, true),
    ('Cult Classic Seeds', array['Cult Classic']::text[], 'boutique_breeder', 'United States', true, true),
    ('Dark Horse Genetics', array['Dark Horse']::text[], 'breeder', 'United States', true, true),
    ('Dark Horse Genetics Seeds', array[]::text[], 'breeder', 'United States', true, true),
    ('Dungeons Vault Genetics', array['Dungeon''s Vault']::text[], 'boutique_breeder', 'United States', true, true),
    ('Dying Breed Seeds', array['Dying Breed']::text[], 'boutique_breeder', 'United States', true, true),
    ('Emerald Mountain Legacy', array['Emerald Mountain']::text[], 'legacy_genetics', 'United States', true, true),
    ('Envy Genetics', array['Envy']::text[], 'boutique_breeder', 'United States', true, true),
    ('Family Tree Seeds', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Fire Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Fresh Coast Seed Company', array['Fresh Coast']::text[], 'boutique_breeder', 'United States', true, true),
    ('Gage Green Group', array['Gage Green']::text[], 'legacy_genetics', 'United States', true, true),
    ('Ganja Rebel Seeds', array['Ganja Rebel']::text[], 'breeder', 'United States', true, true),
    ('Genetix Matter', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Green Bodhi', array['Green Bodhi Seeds']::text[], 'breeder', 'United States', true, true),
    ('Greenpoint Seeds', array['Greenpoint']::text[], 'seed_bank', 'United States', true, true),
    ('Grimm Brothers Seeds', array[]::text[], 'legacy_genetics', 'United States', true, true),
    ('Hazeman Seeds', array['Hazeman']::text[], 'legacy_genetics', 'United States', true, true),
    ('Hoku Seed Co', array['Hoku Seeds']::text[], 'breeder', 'United States', true, true),
    ('Hyp3rids', array['Hyp3rids Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Irie Genetics', array['Irie']::text[], 'breeder', 'United States', true, true),
    ('Jaws Genetics', array[]::text[], 'legacy_genetics', 'United States', true, true),
    ('Katsu Seeds', array['Katsu']::text[], 'legacy_genetics', 'United States', true, true),
    ('Kingdom Organic Seeds', array['Kingdom Organic']::text[], 'breeder', 'United States', true, true),
    ('Kre8 Genetics', array['Kre8']::text[], 'boutique_breeder', 'United States', true, true),
    ('Lucky Dog Seed Co', array['Lucky Dog Seeds']::text[], 'breeder', 'United States', true, true),
    ('Madd Farmer Genetics', array['Madd Farmer']::text[], 'legacy_genetics', 'United States', true, true),
    ('Mass Medical Strains', array['MMS']::text[], 'breeder', 'United States', true, true),
    ('Massive Creations', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Maui Jane Seed Co', array['Maui Jane']::text[], 'boutique_breeder', 'United States', true, true),
    ('Mosca Seeds', array['Mosca']::text[], 'breeder', 'United States', true, true),
    ('MTG Seeds', array['MTG']::text[], 'breeder', 'United States', true, true),
    ('Nerds Genetics', array['Nerds']::text[], 'boutique_breeder', 'United States', true, true),
    ('New420Guy Seeds', array['New 420 Guy']::text[], 'seed_bank', 'United States', true, true),
    ('Night Owl Seeds', array['Night Owl']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Ocean Grown Seeds', array['Ocean Grown']::text[], 'legacy_genetics', 'United States', true, true),
    ('Omuerta Genetix', array['Omuerta']::text[], 'boutique_breeder', 'United States', true, true),
    ('Oregon CBD', array[]::text[], 'breeder', 'United States', true, true),
    ('Pacific Northwest Roots', array['PNW Roots']::text[], 'breeder', 'United States', true, true),
    ('Pacific Seed Bank', array['Pacific Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Pheno Addicts', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Pisces Genetics', array['Pisces']::text[], 'legacy_genetics', 'United States', true, true),
    ('Prolific Coast Seeds', array['Prolific Coast']::text[], 'boutique_breeder', 'United States', true, true),
    ('Puget Sound Seeds', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Purple Caper Seeds', array['Purple Caper']::text[], 'breeder', 'United States', true, true),
    ('Rare Dankness', array['Rare Dankness Seeds']::text[], 'breeder', 'United States', true, true),
    ('Rebel Grown', array['Rebel Grown Seeds']::text[], 'breeder', 'United States', true, true),
    ('Red Scare Seed Company', array['Red Scare']::text[], 'boutique_breeder', 'United States', true, true),
    ('Riot Seeds', array['Riot']::text[], 'legacy_genetics', 'United States', true, true),
    ('RocBud Inc', array['RocBud']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Romulan Genetics', array['Romulan']::text[], 'legacy_genetics', 'United States', true, true),
    ('Second Generation Genetics', array['2nd Generation Genetics']::text[], 'breeder', 'United States', true, true),
    ('Sin City Seeds', array['Sin City']::text[], 'breeder', 'United States', true, true),
    ('Skunk House Genetics', array['Skunk House']::text[], 'boutique_breeder', 'United States', true, true),
    ('SnowHigh Seeds', array['SnowHigh']::text[], 'legacy_genetics', 'United States', true, true),
    ('Socal Seed Vault', array[]::text[], 'seed_bank', 'United States', true, true),
    ('South Bay Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Speakeasy Seedbank', array['Speakeasy Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Strayfox Gardenz', array['Strayfox']::text[], 'boutique_breeder', 'United States', true, true),
    ('Subcool Seeds', array['TGA Subcool']::text[], 'legacy_genetics', 'United States', true, true),
    ('Sunken Treasure Seeds', array['Sunken Treasure']::text[], 'boutique_breeder', 'United States', true, true),
    ('Supernatural Seeds', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Swamp Boys Seeds', array['Swamp Boys']::text[], 'breeder', 'United States', true, true),
    ('Symbiotic Genetics', array['Symbiotic']::text[], 'boutique_breeder', 'United States', true, true),
    ('Taylor Gang Seeds', array['Taylor Gang Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('The Bank Genetics', array[]::text[], 'seed_bank', 'United States', true, true),
    ('The Captain''s Connection', array['Captains Connection']::text[], 'breeder', 'United States', true, true),
    ('ThugPug Genetics', array['Thug Pug']::text[], 'boutique_breeder', 'United States', true, true),
    ('Top Dawg Seeds', array['Top Dawg']::text[], 'legacy_genetics', 'United States', true, true),
    ('Tree Stars Seed Bank', array['Tree Stars']::text[], 'seed_bank', 'United States', true, true),
    ('Twenty Twenty Genetics', array[]::text[], 'breeder', 'United States', true, true),
    ('Useful Seeds', array[]::text[], 'breeder', 'United States', true, true),
    ('Veteran Grown Genetics', array['Veteran Grown']::text[], 'breeder', 'United States', true, true),
    ('Wyeast Farms', array['Wyeast']::text[], 'boutique_breeder', 'United States', true, true),
    ('Yeti Farms', array['Yeti']::text[], 'boutique_breeder', 'United States', true, true),
    ('12/12 Seed Co', array['Twelve Twelve Seed Co']::text[], 'boutique_breeder', 'United States', true, true),
    ('4:20 Genetics', array['420 Genetics']::text[], 'breeder', 'United States', true, true),
    ('AK Bean Brains', array['AKBB']::text[], 'legacy_genetics', 'United States', true, true),
    ('Alpine Genetics USA', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Amish Grown', array['Amish Grown Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Bag Seed Genetics', array[]::text[], 'fallback', null, false, true),
    ('Beleaf Cannabis', array['Beleaf Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Bigworm Genetics', array['Big Worm Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Black Sheep Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Blue Star Seed Co', array['Blue Star Seeds']::text[], 'boutique_breeder', 'United States', true, true),
    ('Bodacious Seeds', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Brisco''s Bargain Beans', array['Briscos Bargain Beans']::text[], 'seed_bank', 'United States', true, true),
    ('Cannarado Seed Co', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Clearwater Genetics', array['Clearwater']::text[], 'boutique_breeder', 'United States', true, true),
    ('Coast of Maine Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Colorado Seed Inc', array['Colorado Seed']::text[], 'breeder', 'United States', true, true),
    ('CopyCat Genetix', array['CopyCat Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Cosmic Wisdom Seeds', array['Cosmic Wisdom']::text[], 'boutique_breeder', 'United States', true, true),
    ('Crickets and Cicada Seeds', array['Crickets & Cicada']::text[], 'breeder', 'United States', true, true),
    ('Cumberland Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('DC Seed Exchange', array['DCSE']::text[], 'marketplace', 'United States', true, true),
    ('Deep Ellum Seed Company', array['Deep Ellum']::text[], 'boutique_breeder', 'United States', true, true),
    ('Deep Space Creations', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Diamond Nugget Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Dragons Flame Genetics', array['Dragon''s Flame']::text[], 'breeder', 'United States', true, true),
    ('East Coast Seed Bank', array['East Coast Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Elev8 Seeds', array['Elev8']::text[], 'breeder', 'United States', true, true),
    ('Empire Breeding Co', array['Empire Breeding']::text[], 'boutique_breeder', 'United States', true, true),
    ('Farmhouse Studio Genetics', array['Farmhouse Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Fat Cat Labs', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Fire Garden Pharms', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Flap Jacks Seed Co', array['Flap Jacks']::text[], 'boutique_breeder', 'United States', true, true),
    ('Forbidden Fruit Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Freak Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Frost Bros Genetics', array['Frost Brothers']::text[], 'boutique_breeder', 'United States', true, true),
    ('Frost Fire Seeds', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Frosty Fire Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Gas Reaper Genetics', array['Gas Reaper']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Genetic Designer', array['The Genetic Designer']::text[], 'boutique_breeder', 'United States', true, true),
    ('Goat Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Golden Road Seed Co', array['Golden Road Seeds']::text[], 'boutique_breeder', 'United States', true, true),
    ('Grandpa''s Stash Seeds', array['Grandpas Stash']::text[], 'legacy_genetics', 'United States', true, true),
    ('Green Fire Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Green Team Genetics', array['The Green Team']::text[], 'boutique_breeder', 'United States', true, true),
    ('Greenwolf Genetics', array['Green Wolf Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Grounded Genetics USA', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Happy Dreams Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Heart and Soil Seeds', array['Heart & Soil']::text[], 'boutique_breeder', 'United States', true, true),
    ('Higher Love Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Humboldt CSI Seeds', array[]::text[], 'breeder', 'United States', true, true),
    ('Humboldt Terp Council', array['HTC']::text[], 'collective', 'United States', true, true),
    ('Insane Seed Posse', array['Insane Seeds']::text[], 'collective', 'United States', true, true),
    ('Jinxproof Genetics', array['Jinxproof']::text[], 'breeder', 'United States', true, true),
    ('Jordan of the Islands', array['JOTI']::text[], 'legacy_genetics', 'Canada', true, true),
    ('Kakleberry Farms', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Khalifa Genetics', array['Khalifa']::text[], 'breeder', 'France', true, true),
    ('KushBrothers Seeds', array['Kush Brothers']::text[], 'boutique_breeder', 'United States', true, true),
    ('La Plata Labs', array[]::text[], 'legacy_genetics', 'United States', true, true),
    ('Laughing Hyena Seeds', array['Laughing Hyena']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Lemonhoko', array['Lemonhoko Seeds']::text[], 'boutique_breeder', 'United States', true, true),
    ('Lovin'' in Her Eyes', array['Lovin in Her Eyes']::text[], 'boutique_breeder', 'United States', true, true),
    ('Lumberjack Seed Source', array['Lumberjack Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Magic Spirit Seed Co', array['Magic Spirit']::text[], 'boutique_breeder', 'United States', true, true),
    ('Mandala Seeds', array['Mandala']::text[], 'legacy_genetics', 'Spain', true, true),
    ('Mandalorian Genetics', array['Mandalorian']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Massachusetts Super Skunk', array['MSS']::text[], 'legacy_genetics', 'United States', true, true),
    ('Mendocino Seed Company', array['Mendocino Seeds']::text[], 'legacy_genetics', 'United States', true, true),
    ('Mendocino Twenty20', array[]::text[], 'breeder', 'United States', true, true),
    ('Michigan Marijuana Seed Club', array['MMSC']::text[], 'collective', 'United States', true, true),
    ('Midnight Roots', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Mimosa Nursery', array[]::text[], 'breeder', 'United States', true, true),
    ('Mountain Organics', array['Mountain Organics Seeds']::text[], 'legacy_genetics', 'United States', true, true),
    ('Mountain Top Seed Bank', array['Mountain Top Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Mr. Soul', array['Mr Soul']::text[], 'legacy_genetics', 'United States', true, true),
    ('Nasha Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Nature Farm Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Neptune Seed Bank', array['Neptune Seeds']::text[], 'marketplace', 'United States', true, true),
    ('New England Seed Co', array['New England Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('New Kids on the Block Genetics', array['NKOTB Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Nirvana Seeds', array['Nirvana Seed Bank']::text[], 'seed_bank', 'Netherlands', true, true),
    ('Noble Seeds', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('North Atlantic Seed Company', array['NASC']::text[], 'marketplace', 'United States', true, true),
    ('Old School Chronic', array[]::text[], 'legacy_genetics', 'United States', true, true),
    ('Old School Genetics', array['Old School Genetics Seeds']::text[], 'legacy_genetics', 'Spain', true, true),
    ('Oni Seed Co', array['Oni Seeds']::text[], 'boutique_breeder', 'United States', true, true),
    ('Oregon Elite Seeds', array['Oregon Elite']::text[], 'marketplace', 'United States', true, true),
    ('Pack Banditz Seedbank', array['Pack Banditz']::text[], 'seed_bank', 'United States', true, true),
    ('Philosopher Seeds', array['Philosopher']::text[], 'breeder', 'Spain', true, true),
    ('Pips Weed Seeds', array['Pips Weed']::text[], 'boutique_breeder', 'United States', true, true),
    ('Platinum Seed Bank', array['Platinum Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Pot Valley Seeds', array['Pot Valley']::text[], 'seed_bank', 'United States', true, true),
    ('Prairie State Genetix', array['Prairie State Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Pure Michigan Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Raw Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Red River Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Regenerative Seed Co', array['Regenerative Seeds']::text[], 'breeder', 'United States', true, true),
    ('Rocky Mountain High Seeds', array['RMH Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Sacred Cut Seed Co', array['Sacred Cut']::text[], 'boutique_breeder', 'United States', true, true),
    ('Santa Cruz Goat Farm', array['SC Goat Farm']::text[], 'boutique_breeder', 'United States', true, true),
    ('Savage Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Second City Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Seeds Here Now', array['SHN']::text[], 'marketplace', 'United States', true, true),
    ('Seeds for Me', array[]::text[], 'marketplace', 'United States', true, true),
    ('Seedsherenow', array[]::text[], 'marketplace', 'United States', true, true),
    ('Sensi Seeds Research', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Shwale', array['Shwale Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Sierra Nevada Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Silverback Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Socal Seeds', array[]::text[], 'seed_bank', 'United States', true, true),
    ('South Fork Seed Collective', array['South Fork Seeds']::text[], 'collective', 'United States', true, true),
    ('Southern Oregon Seeds', array[]::text[], 'seed_bank', 'United States', true, true),
    ('Stardawg Seed Co', array['Stardawg Seeds']::text[], 'boutique_breeder', 'United States', true, true),
    ('Stoney Girl Gardens', array['Stoney Girl']::text[], 'legacy_genetics', 'United States', true, true),
    ('Strainly', array[]::text[], 'marketplace', 'Canada', true, true),
    ('Surfr Seeds', array['Surfr Seed Co']::text[], 'boutique_breeder', 'United States', true, true),
    ('Swami Organic Seed', array['Swami Seeds']::text[], 'legacy_genetics', 'United States', true, true),
    ('Terp Fi3nd', array['Terp Fiend']::text[], 'boutique_breeder', 'United States', true, true),
    ('Terp Hogz', array['Terp Hogz Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Terp Town', array['Terp Town Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Terpy Seeds', array[]::text[], 'seed_bank', 'United States', true, true),
    ('The Cali Seed Store', array[]::text[], 'seed_bank', 'United States', true, true),
    ('The Nature Farm', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('The Plug Seedbank', array['The Plug Seeds']::text[], 'seed_bank', 'United Kingdom', true, true),
    ('The Seed Bazaar', array['Seed Bazaar']::text[], 'marketplace', 'United States', true, true),
    ('Tiger Trees', array['Tiger Trees Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Tony Green''s Tortured Beans', array['Tony Greens Tortured Beans']::text[], 'breeder', 'United States', true, true),
    ('Trichome Jungle Seeds', array['Trichome Jungle']::text[], 'breeder', 'United Kingdom', true, true),
    ('UFO Genetics', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('United Seed Bank', array['United Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Upstate Seed Company', array['Upstate Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Vader OG Genetics', array['Vader OG']::text[], 'legacy_genetics', 'United States', true, true),
    ('White Buffalo Seed Collective', array['White Buffalo Seeds']::text[], 'collective', 'United States', true, true),
    ('White Label Genetics', array[]::text[], 'breeder', null, true, true),
    ('Wicked Pissah Seeds', array['Wicked Pissah']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Wolfpack Selections', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Zmoothiez', array['Zmoothiez Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Mephisto Genetics', array['Mephisto']::text[], 'autoflower_breeder', 'Spain', true, true),
    ('Fast Buds', array['420 Fast Buds']::text[], 'autoflower_breeder', 'Spain', true, true),
    ('Dutch Passion', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('Sweet Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Barney''s Farm', array['Barneys Farm']::text[], 'breeder', 'Netherlands', true, true),
    ('Sensi Seeds', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Serious Seeds', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Green House Seed Co', array['Green House Seeds']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Mr. Nice Seedbank', array['Mr Nice Seeds']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Paradise Seeds', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('TH Seeds', array['T.H. Seeds']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Soma Seeds', array['Soma Sacred Seeds']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Flying Dutchmen Seeds', array['The Flying Dutchmen']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Sagarmatha Seeds', array['Sagarmatha']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('KC Brains', array['KC Brains Holland']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Homegrown Fantaseeds', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Royal Queen Seeds', array['RQS']::text[], 'seed_bank', 'Spain', true, true),
    ('Dinafem Seeds', array['Dinafem']::text[], 'legacy_genetics', 'Spain', true, true),
    ('Kannabia Seeds', array['Kannabia']::text[], 'breeder', 'Spain', true, true),
    ('Pyramid Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Delicious Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Eva Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Positronics Seeds', array['Positronics']::text[], 'legacy_genetics', 'Spain', true, true),
    ('Ace Seeds', array['ACE']::text[], 'legacy_genetics', 'Spain', true, true),
    ('Cannabiogen', array[]::text[], 'legacy_genetics', 'Spain', true, true),
    ('Reggae Seeds', array[]::text[], 'legacy_genetics', 'Spain', true, true),
    ('Tropical Seeds Company', array['Tropical Seeds']::text[], 'breeder', 'Spain', true, true),
    ('Medical Seeds', array['Medical Seeds Co']::text[], 'breeder', 'Spain', true, true),
    ('Gea Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Genehtik Seeds', array['Genehtik']::text[], 'breeder', 'Spain', true, true),
    ('Ministry of Cannabis', array[]::text[], 'breeder', 'Spain', true, true),
    ('Bulk Seed Bank', array[]::text[], 'seed_bank', 'Spain', true, true),
    ('Blimburn Seeds', array['Blimburn']::text[], 'seed_bank', 'Spain', true, true),
    ('World of Seeds', array['World of Seeds Bank']::text[], 'seed_bank', 'Spain', true, true),
    ('Advanced Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Ripper Seeds', array['Ripper']::text[], 'breeder', 'Spain', true, true),
    ('Seedstockers', array['Seed Stockers']::text[], 'seed_bank', 'Spain', true, true),
    ('BSB Genetics', array['BSB']::text[], 'breeder', 'Spain', true, true),
    ('Anesia Seeds', array['Anesia']::text[], 'breeder', 'Spain', true, true),
    ('Plant of Life Seeds', array['Plant of Life']::text[], 'breeder', 'Spain', true, true),
    ('Vision Seeds', array[]::text[], 'seed_bank', 'Netherlands', true, true),
    ('Spliff Seeds', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('Amsterdam Genetics', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('Amsterdam Seed Center', array['Amsterdam Seed Centre']::text[], 'marketplace', 'Netherlands', true, true),
    ('Seed Supreme', array[]::text[], 'marketplace', 'United Kingdom', true, true),
    ('Attitude Seedbank', array['The Attitude']::text[], 'marketplace', 'United Kingdom', true, true),
    ('Herbies Seeds', array['Herbies Head Shop']::text[], 'marketplace', 'Spain', true, true),
    ('Seedsman', array[]::text[], 'marketplace', 'Spain', true, true),
    ('Seed City', array[]::text[], 'marketplace', 'United Kingdom', true, true),
    ('The Vault Cannabis Seeds Store', array['The Vault']::text[], 'marketplace', 'United Kingdom', true, true),
    ('Original Sensible Seeds', array['Sensible Seeds']::text[], 'seed_bank', 'Spain', true, true),
    ('Original Seeds Store', array[]::text[], 'marketplace', 'Spain', true, true),
    ('Single Seed Centre', array['The Single Seed Centre']::text[], 'marketplace', 'United Kingdom', true, true),
    ('Pick and Mix Seeds', array['Pick n Mix Seeds']::text[], 'marketplace', 'United Kingdom', true, true),
    ('Grizzly Seed Bank', array['Grizzly Seeds']::text[], 'marketplace', 'United Kingdom', true, true),
    ('London Seed Centre', array['London Seed Center']::text[], 'marketplace', 'United Kingdom', true, true),
    ('Discount Cannabis Seeds', array['DCS']::text[], 'marketplace', 'United Kingdom', true, true),
    ('Gorilla Seeds', array['Gorilla Seed Bank']::text[], 'marketplace', 'United Kingdom', true, true),
    ('Seeds24', array[]::text[], 'marketplace', 'Netherlands', true, true),
    ('Alchimia Grow Shop', array['Alchimia']::text[], 'marketplace', 'Spain', true, true),
    ('Zamnesia Seeds', array['Zamnesia']::text[], 'marketplace', 'Netherlands', true, true),
    ('Linda Seeds', array[]::text[], 'marketplace', 'Spain', true, true),
    ('Oaseeds', array['OA Seeds']::text[], 'marketplace', 'Spain', true, true),
    ('Seeds66', array[]::text[], 'marketplace', 'Germany', true, true),
    ('Mr. Hanf', array['Mr Hanf']::text[], 'marketplace', 'Germany', true, true),
    ('Samenwahl', array[]::text[], 'marketplace', 'Germany', true, true),
    ('Cannapot', array[]::text[], 'marketplace', 'Austria', true, true),
    ('SeedFinder Shop', array[]::text[], 'marketplace', 'Germany', true, true),
    ('Hanf & Hanf', array['Hanf und Hanf']::text[], 'marketplace', 'Germany', true, true),
    ('SensorySeeds', array['Sensory Seeds']::text[], 'marketplace', 'Italy', true, true),
    ('Semillas de Marihuana', array[]::text[], 'marketplace', 'Spain', true, true),
    ('Cannabis Seeds Outlet', array[]::text[], 'marketplace', 'United Kingdom', true, true),
    ('MSNL Seed Bank', array['MSNL']::text[], 'marketplace', 'United Kingdom', true, true),
    ('I Love Growing Marijuana', array['ILGM']::text[], 'seed_bank', 'United States', true, true),
    ('Crop King Seeds', array['Crop King']::text[], 'seed_bank', 'Canada', true, true),
    ('Quebec Cannabis Seeds', array['QCS']::text[], 'seed_bank', 'Canada', true, true),
    ('Canuk Seeds', array['Canuk']::text[], 'seed_bank', 'Canada', true, true),
    ('True North Seed Bank', array['True North']::text[], 'marketplace', 'Canada', true, true),
    ('Vancouver Seed Bank', array['VSB']::text[], 'seed_bank', 'Canada', true, true),
    ('Next Generation Seed Company', array['Next Generation Seeds']::text[], 'legacy_genetics', 'Canada', true, true),
    ('Dr. Greenthumb Seeds', array['Dr Greenthumb']::text[], 'legacy_genetics', 'Canada', true, true),
    ('Peak Seeds BC', array['Peak Seeds']::text[], 'legacy_genetics', 'Canada', true, true),
    ('BC Bud Depot', array['BCBD']::text[], 'legacy_genetics', 'Canada', true, true),
    ('Federation Seed Company', array['Federation Seeds']::text[], 'legacy_genetics', 'Canada', true, true),
    ('House of the Great Gardener', array['Great Gardener']::text[], 'legacy_genetics', 'Canada', true, true),
    ('Jah Seeds', array[]::text[], 'legacy_genetics', 'Canada', true, true),
    ('Jordan of The Islands Seeds', array[]::text[], 'legacy_genetics', 'Canada', true, true),
    ('Montreal Cannabis Seeds', array['MCS']::text[], 'seed_bank', 'Canada', true, true),
    ('Niagara Seed Bank', array[]::text[], 'seed_bank', 'Canada', true, true),
    ('White Buffalo Genetics', array[]::text[], 'breeder', 'Canada', true, true),
    ('Weathered Islands Craft Cannabis Seeds', array['Weathered Islands']::text[], 'breeder', 'Canada', true, true),
    ('Sacred Seed', array['Sacred Seeds']::text[], 'legacy_genetics', 'United States', true, true),
    ('Super Sativa Seed Club', array['SSSC']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Nevil''s Seed Bank', array['The Seed Bank of Holland']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Cultivators Choice', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Skunk VA', array['SkunkVA']::text[], 'legacy_genetics', 'United States', true, true),
    ('Old World Genetics', array[]::text[], 'legacy_genetics', 'United States', true, true),
    ('MediSeed Man', array[]::text[], 'seed_bank', 'Australia', true, true),
    ('Aussie Canna Seeds', array[]::text[], 'seed_bank', 'Australia', true, true),
    ('Caveman Seeds', array[]::text[], 'seed_bank', 'Australia', true, true),
    ('Frosty Flowers', array[]::text[], 'marketplace', 'Canada', true, true),
    ('Hemp Depot Canada', array['Hemp Depot']::text[], 'seed_bank', 'Canada', true, true),
    ('Reeferman Seeds', array['Reeferman']::text[], 'legacy_genetics', 'Canada', true, true),
    ('Kind Seed Co', array['Kind Seeds']::text[], 'seed_bank', 'Canada', true, true),
    ('Ontario Seed Bank', array[]::text[], 'seed_bank', 'Canada', true, true),
    ('Truenorth Genetics', array['True North Genetics']::text[], 'breeder', 'Canada', true, true),
    ('White Widow Seeds', array[]::text[], 'seed_bank', null, true, true),
    ('Ace of Spades Genetics', array[]::text[], 'boutique_breeder', null, true, true),
    ('Auto Seeds', array['Auto Seeds UK']::text[], 'autoflower_breeder', 'United Kingdom', true, true),
    ('Auto Seeds Co', array[]::text[], 'autoflower_breeder', 'United Kingdom', true, true),
    ('FastBuds Genetics', array[]::text[], 'autoflower_breeder', 'Spain', true, true),
    ('Short Stuff Seeds', array['Short Stuff']::text[], 'autoflower_breeder', 'United Kingdom', true, true),
    ('Flash Seeds', array[]::text[], 'autoflower_breeder', 'Spain', true, true),
    ('Joint Doctor Seeds', array['The Joint Doctor']::text[], 'autoflower_breeder', 'Canada', true, true),
    ('Lowryder Seeds', array['Lowryder']::text[], 'autoflower_breeder', 'Canada', true, true),
    ('Stitch Seeds', array['Stitch']::text[], 'autoflower_breeder', 'Spain', true, true),
    ('Autoflower Portal', array[]::text[], 'collective', null, true, true),
    ('Twisted Tree Autoflowers', array['Twisted Tree']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Magic Strains', array[]::text[], 'autoflower_breeder', 'United States', true, true),
    ('Binary Selections', array[]::text[], 'autoflower_breeder', 'United States', true, true),
    ('Gnome Automatics', array['Gnome Autos']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Atlas Seed', array['Atlas Seeds']::text[], 'breeder', 'United States', true, true),
    ('Photon Pharms', array[]::text[], 'autoflower_breeder', 'United States', true, true),
    ('Full Duplex AFN', array['Full Duplex']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Chef Anna White Label', array['Chef Anna']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Terp Treez Co', array['Terp Treez']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Firebudz Genetics', array['Firebudz']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Jean-O''s Genetics', array['Jean Os Genetics']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Speedrun Seeds', array['Speedrun']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Dream Beans', array['Dream Beans Genetics']::text[], 'autoflower_breeder', 'United States', true, true),
    ('Frostfire Autoflowers', array[]::text[], 'autoflower_breeder', 'United States', true, true),
    ('Twenty20 Autoflower', array[]::text[], 'autoflower_breeder', 'United States', true, true),
    ('Dutch Passion AutoFem', array[]::text[], 'autoflower_breeder', 'Netherlands', true, true),
    ('Sensi Seeds Automatic', array[]::text[], 'autoflower_breeder', 'Netherlands', true, true),
    ('Green House Seeds Auto', array[]::text[], 'autoflower_breeder', 'Netherlands', true, true),
    ('Royal Queen Seeds Automatic', array[]::text[], 'autoflower_breeder', 'Spain', true, true),
    ('Sweet Seeds Autoflowering', array[]::text[], 'autoflower_breeder', 'Spain', true, true),
    ('Female Seeds', array['Female Seeds NL']::text[], 'breeder', 'Netherlands', true, true),
    ('Bomb Seeds', array[]::text[], 'breeder', 'United Kingdom', true, true),
    ('CBD Crew', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('CBD Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Ceres Seeds', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('De Sjamaan Seeds', array['De Sjamaan']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Dutch Flowers', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Dutch Quality Seeds', array[]::text[], 'seed_bank', 'Netherlands', true, true),
    ('DutchFem Seeds', array['Dutch Fem']::text[], 'breeder', 'Netherlands', true, true),
    ('Eskobar Seeds', array['Eskobar']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Family Ganjah', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('Flying Seeds', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('Green Label Seeds', array['Greenlabel Seeds']::text[], 'breeder', 'Netherlands', true, true),
    ('High Supplies', array[]::text[], 'seed_bank', 'Netherlands', true, true),
    ('Hortilab Seeds', array['Hortilab']::text[], 'breeder', 'Netherlands', true, true),
    ('Hy-Pro Seeds', array['Hy Pro Seeds']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Kiwiseeds', array['Kiwi Seeds']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Lady Sativa Genetics', array['Lady Sativa']::text[], 'breeder', 'Netherlands', true, true),
    ('Magus Genetics', array['Magus']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('No Mercy Seeds', array['No Mercy']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Opengrow Seeds', array['OpenGrow']::text[], 'collective', 'Netherlands', true, true),
    ('Power Seeds', array[]::text[], 'seed_bank', 'Netherlands', true, true),
    ('Royal Dutch Genetics', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('Seedism Seeds', array['Seedism']::text[], 'breeder', 'Netherlands', true, true),
    ('Sumo Seeds', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('T.H.Seeds Amsterdam', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('The Bulldog Seeds', array['Bulldog Seeds']::text[], 'breeder', 'Netherlands', true, true),
    ('The Kush Brothers', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('Victory Seeds', array[]::text[], 'seed_bank', 'Netherlands', true, true),
    ('White Label Seed Company', array['White Label Seeds']::text[], 'seed_bank', 'Netherlands', true, true),
    ('Zambeza Seeds', array['Zambeza']::text[], 'seed_bank', 'Netherlands', true, true),
    ('Big Buddha Seeds', array['Big Buddha']::text[], 'legacy_genetics', 'United Kingdom', true, true),
    ('Big Head Seeds', array[]::text[], 'breeder', 'United Kingdom', true, true),
    ('Black Skull Seeds', array['Black Skull']::text[], 'breeder', 'United Kingdom', true, true),
    ('Cali Weed Seeds', array[]::text[], 'seed_bank', 'United Kingdom', true, true),
    ('Connoisseur Genetics', array['Connoisseur']::text[], 'breeder', 'United Kingdom', true, true),
    ('Crazy X Seeds', array['Crazy X']::text[], 'legacy_genetics', 'United Kingdom', true, true),
    ('Devil''s Harvest Seeds', array['Devils Harvest']::text[], 'breeder', 'United Kingdom', true, true),
    ('Dr Krippling Seeds', array['Dr Krippling']::text[], 'breeder', 'United Kingdom', true, true),
    ('Dr Underground', array['Dr Underground Seeds']::text[], 'breeder', 'Spain', true, true),
    ('Emerald Triangle Seeds', array['Emerald Triangle']::text[], 'legacy_genetics', 'United Kingdom', true, true),
    ('Expert Seeds', array[]::text[], 'breeder', 'United Kingdom', true, true),
    ('Kaliman Seeds', array['Kaliman']::text[], 'legacy_genetics', 'United Kingdom', true, true),
    ('Lineage Genetics', array['Lineage']::text[], 'breeder', 'United Kingdom', true, true),
    ('London City Genetics', array[]::text[], 'boutique_breeder', 'United Kingdom', true, true),
    ('Ministry of Cannabis UK', array[]::text[], 'breeder', 'United Kingdom', true, true),
    ('OG Raskal Genetics', array['OGRaskal']::text[], 'legacy_genetics', 'United States', true, true),
    ('Original Big Buddha Family Farms', array['OBBFF']::text[], 'legacy_genetics', 'United Kingdom', true, true),
    ('Real Gorilla Seeds', array['Real Gorilla']::text[], 'seed_bank', 'United Kingdom', true, true),
    ('Real Seed Company', array['The Real Seed Company']::text[], 'legacy_genetics', 'United Kingdom', true, true),
    ('Real Seed Co', array[]::text[], 'legacy_genetics', 'United Kingdom', true, true),
    ('Red Scare Seed Co UK', array[]::text[], 'boutique_breeder', 'United Kingdom', true, true),
    ('Scottish Seed Bank', array[]::text[], 'seed_bank', 'United Kingdom', true, true),
    ('Short Stuff Seedbank', array[]::text[], 'autoflower_breeder', 'United Kingdom', true, true),
    ('SickMeds Seeds', array['SickMeds']::text[], 'breeder', 'United Kingdom', true, true),
    ('Sonic Seeds', array[]::text[], 'legacy_genetics', 'United Kingdom', true, true),
    ('UGORG', array['Underground Originals']::text[], 'legacy_genetics', 'United Kingdom', true, true),
    ('Urban Legends', array['Urban Legends Seeds']::text[], 'seed_bank', 'United Kingdom', true, true),
    ('Wild Rose Seed Co', array['Wild Rose Seeds']::text[], 'breeder', 'United Kingdom', true, true),
    ('7 East Genetics', array['Seven East Genetics']::text[], 'breeder', 'Canada', true, true),
    ('AKG Seeds', array[]::text[], 'breeder', 'Canada', true, true),
    ('Beanstock Seeds', array['Beanstock']::text[], 'seed_bank', 'Canada', true, true),
    ('Black Tuna Seeds', array[]::text[], 'breeder', 'Canada', true, true),
    ('Blue Hemp Seeds', array[]::text[], 'legacy_genetics', 'Switzerland', true, true),
    ('CannaBioGen Seeds', array[]::text[], 'legacy_genetics', 'Spain', true, true),
    ('CannaPot Seeds', array[]::text[], 'marketplace', 'Austria', true, true),
    ('CannaSeed Bank', array['Canna Seed Bank']::text[], 'seed_bank', 'Canada', true, true),
    ('Coastal Mary Seeds', array['Coastal Mary']::text[], 'seed_bank', 'Canada', true, true),
    ('Elite 613 Genetics', array['613 Genetics']::text[], 'boutique_breeder', 'Canada', true, true),
    ('Freedom of Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Freedom Seeds', array[]::text[], 'seed_bank', 'United Kingdom', true, true),
    ('Hash Plant Seeds', array[]::text[], 'legacy_genetics', null, true, true),
    ('Highrise Seeds', array['High Rise Seeds']::text[], 'legacy_genetics', 'Canada', true, true),
    ('Joti Seeds', array[]::text[], 'legacy_genetics', 'Canada', true, true),
    ('Kind Seed Company', array[]::text[], 'seed_bank', 'Canada', true, true),
    ('LaMota Seeds', array['La Mota']::text[], 'marketplace', 'Spain', true, true),
    ('Lizard Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Medical Marijuana Genetics', array['MM Genetics']::text[], 'breeder', 'United Kingdom', true, true),
    ('Nectar Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Original Delicatessen Seeds', array['Delicatessen Seeds']::text[], 'breeder', 'Spain', true, true),
    ('Pepita Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Pop Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Rare Seed Company', array[]::text[], 'seed_bank', 'Canada', true, true),
    ('R-Kiem Seeds', array['R Kiem Seeds']::text[], 'breeder', 'Spain', true, true),
    ('Sagarmatha Seeds NL', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Samsara Seeds', array['Samsara']::text[], 'legacy_genetics', 'Spain', true, true),
    ('Seeds of Life', array[]::text[], 'breeder', 'Spain', true, true),
    ('Spanish Seeds', array[]::text[], 'seed_bank', 'Spain', true, true),
    ('Super Strains', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('Tanska Seed Development', array['Tanska Seeds']::text[], 'breeder', 'Canada', true, true),
    ('The Cali Connection Europe', array[]::text[], 'breeder', 'Spain', true, true),
    ('The Landrace Team', array[]::text[], 'collective', 'Spain', true, true),
    ('Tiki Seedbank', array['Tiki Seeds']::text[], 'legacy_genetics', 'France', true, true),
    ('Trikoma Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Tropical Seeds Co', array[]::text[], 'breeder', 'Spain', true, true),
    ('Underground Seeds Collective', array['USC Seeds']::text[], 'collective', 'France', true, true),
    ('Victory Seeds NL', array[]::text[], 'seed_bank', 'Netherlands', true, true),
    ('Viking Gardens', array[]::text[], 'breeder', 'Canada', true, true),
    ('VIP Seeds', array[]::text[], 'seed_bank', 'Spain', true, true),
    ('Vision Seeds NL', array[]::text[], 'seed_bank', 'Netherlands', true, true),
    ('World of Seeds Spain', array[]::text[], 'seed_bank', 'Spain', true, true),
    ('Alpine Seeds', array[]::text[], 'breeder', 'Switzerland', true, true),
    ('Alpine Genetics', array[]::text[], 'breeder', 'Switzerland', true, true),
    ('ApeOrigin', array['ApeOrigin Seeds']::text[], 'breeder', 'Germany', true, true),
    ('Big Seedbank', array[]::text[], 'seed_bank', 'Germany', true, true),
    ('Cannamedical Seeds', array[]::text[], 'breeder', 'Germany', true, true),
    ('CannaPot Austria', array[]::text[], 'marketplace', 'Austria', true, true),
    ('CannaSeed Store', array[]::text[], 'marketplace', 'Germany', true, true),
    ('Deaflora Seeds', array['Deaflora']::text[], 'breeder', 'Germany', true, true),
    ('Der Hanf Shop', array[]::text[], 'marketplace', 'Germany', true, true),
    ('Exotic Seed', array['Exotic Seed Spain']::text[], 'breeder', 'Spain', true, true),
    ('Female Seeds Germany', array[]::text[], 'seed_bank', 'Germany', true, true),
    ('Green Buzz Seeds', array['Green Buzz']::text[], 'breeder', 'Germany', true, true),
    ('Hanf Samen', array[]::text[], 'marketplace', 'Germany', true, true),
    ('Hanf Seeds', array[]::text[], 'marketplace', 'Germany', true, true),
    ('Hesi Seeds', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('Holy Smoke Seeds', array['Holy Smoke']::text[], 'legacy_genetics', 'Switzerland', true, true),
    ('Ingemar Seeds', array['Ingemar']::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Joint Doctor Lowryder', array[]::text[], 'legacy_genetics', 'Canada', true, true),
    ('Kaly Seeds', array[]::text[], 'breeder', 'France', true, true),
    ('Kera Seeds', array[]::text[], 'seed_bank', 'Netherlands', true, true),
    ('La Semilla Automatica', array[]::text[], 'autoflower_breeder', 'Spain', true, true),
    ('Mama Editions Seeds', array[]::text[], 'breeder', 'France', true, true),
    ('Mandala Seeds Europe', array[]::text[], 'legacy_genetics', 'Spain', true, true),
    ('Ministry of Cannabis Seeds', array[]::text[], 'breeder', 'Spain', true, true),
    ('Mr. Hide Seeds', array['Mr Hide Seeds']::text[], 'breeder', 'Spain', true, true),
    ('Nirvana Shop', array[]::text[], 'marketplace', 'Netherlands', true, true),
    ('Nordic Genetics', array[]::text[], 'breeder', 'Denmark', true, true),
    ('Original Sensible Seed Co', array[]::text[], 'seed_bank', 'Spain', true, true),
    ('PevGrow', array['Pev Grow']::text[], 'marketplace', 'Spain', true, true),
    ('Pure Seeds', array[]::text[], 'seed_bank', 'Germany', true, true),
    ('Royal Queen Seeds Germany', array[]::text[], 'seed_bank', 'Germany', true, true),
    ('Sagarmatha Seedbank', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('Seeds Mafia', array['SeedsMafia']::text[], 'seed_bank', 'Spain', true, true),
    ('Serious Seeds Holland', array[]::text[], 'legacy_genetics', 'Netherlands', true, true),
    ('SuperCBDx', array['Super CBDx']::text[], 'breeder', 'Spain', true, true),
    ('Swiss Seeds', array[]::text[], 'seed_bank', 'Switzerland', true, true),
    ('The Bulldog Seeds Amsterdam', array[]::text[], 'breeder', 'Netherlands', true, true),
    ('Top Tao Seeds', array['Top Tao']::text[], 'breeder', 'Czech Republic', true, true),
    ('Victory Seed Company', array[]::text[], 'seed_bank', 'Netherlands', true, true),
    ('White Label Seeds NL', array[]::text[], 'seed_bank', 'Netherlands', true, true),
    ('World Wide Seeds', array[]::text[], 'marketplace', 'Spain', true, true),
    ('Zativo Seeds', array['Zativo']::text[], 'marketplace', 'Netherlands', true, true),
    ('Zenseeds', array['Zen Seeds']::text[], 'breeder', 'Denmark', true, true),
    ('Ace Seed Bank', array[]::text[], 'marketplace', 'Spain', true, true),
    ('Alpha Seeds', array[]::text[], 'seed_bank', null, true, true),
    ('Area 51 Seed Bank', array['Area 51 Seeds']::text[], 'marketplace', 'United States', true, true),
    ('Baked Beans Cannabis Seeds', array['Baked Beans']::text[], 'seed_bank', 'United States', true, true),
    ('Bank Genetics', array[]::text[], 'seed_bank', 'United States', true, true),
    ('Bean Basement', array[]::text[], 'collective', 'United States', true, true),
    ('Bean Hoarder', array['Bean Hoarder Seeds']::text[], 'collective', 'United States', true, true),
    ('Bean Poppin', array['Bean Poppin Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('Blackbird Preservations', array['Blackbird']::text[], 'collective', 'United States', true, true),
    ('BreedBay', array[]::text[], 'marketplace', 'United Kingdom', true, true),
    ('Canna Collector', array['Canna Collector Seeds']::text[], 'marketplace', 'United States', true, true),
    ('Canna Pot Seeds', array[]::text[], 'marketplace', 'Austria', true, true),
    ('Cannabis Seed Bank of Maine', array['Maine Seed Bank']::text[], 'seed_bank', 'United States', true, true),
    ('Cannabis Seeds USA', array[]::text[], 'marketplace', 'United States', true, true),
    ('CannaGen Seed Company', array['CannaGen']::text[], 'breeder', 'United States', true, true),
    ('CannaRebels', array['Canna Rebels']::text[], 'collective', 'United States', true, true),
    ('Seeds Direct', array[]::text[], 'marketplace', null, true, true),
    ('Seeds For The People', array[]::text[], 'collective', 'United States', true, true),
    ('Seeds of Horror', array[]::text[], 'boutique_breeder', 'United States', true, true),
    ('Seedsman White Label', array[]::text[], 'seed_bank', 'Spain', true, true),
    ('SeedSource', array['Seed Source']::text[], 'marketplace', null, true, true),
    ('Seed Vault Canada', array[]::text[], 'seed_bank', 'Canada', true, true),
    ('Seed Vault UK', array[]::text[], 'seed_bank', 'United Kingdom', true, true),
    ('Seed Vault USA', array[]::text[], 'seed_bank', 'United States', true, true),
    ('Seed Canary', array[]::text[], 'marketplace', 'Canada', true, true),
    ('Seed Fair', array[]::text[], 'marketplace', null, true, true),
    ('Seed Heaven', array[]::text[], 'marketplace', null, true, true),
    ('Seed King', array['Seed King Seeds']::text[], 'seed_bank', 'Canada', true, true),
    ('Seed King Express', array[]::text[], 'seed_bank', 'Canada', true, true),
    ('Seed Kingdom', array[]::text[], 'seed_bank', 'Canada', true, true),
    ('Seed Pharm', array['Seed Pharm Genetics']::text[], 'boutique_breeder', 'United States', true, true),
    ('Seed Ranch', array['The Seed Ranch']::text[], 'marketplace', 'United States', true, true),
    ('Seed Select', array[]::text[], 'seed_bank', null, true, true),
    ('Seed Source Genetics', array[]::text[], 'breeder', null, true, true),
    ('Seed Stock', array[]::text[], 'marketplace', null, true, true),
    ('Seed Traders', array['Seed Traders Collective']::text[], 'collective', null, true, true),
    ('Seed Vault Genetics', array[]::text[], 'breeder', null, true, true),
    ('Seedbank.com', array['Seedbank']::text[], 'marketplace', null, true, true),
    ('Seeds Bank', array[]::text[], 'marketplace', null, true, true),
    ('Seeds Canada', array[]::text[], 'marketplace', 'Canada', true, true),
    ('Seeds Europe', array[]::text[], 'marketplace', null, true, true),
    ('Seeds Genetics', array[]::text[], 'breeder', null, true, true),
    ('Seeds of Creation', array[]::text[], 'boutique_breeder', null, true, true),
    ('Seeds of Green', array[]::text[], 'seed_bank', null, true, true),
    ('Seeds of Love', array[]::text[], 'collective', null, true, true),
    ('Seeds of Plenty', array[]::text[], 'seed_bank', null, true, true),
    ('Seeds R Us', array[]::text[], 'marketplace', null, true, true),
    ('Seeds to Sow', array[]::text[], 'collective', null, true, true),
    ('Seeds Unlimited', array[]::text[], 'marketplace', null, true, true),
    ('Seeds World', array[]::text[], 'marketplace', null, true, true),
    ('Smoke Signals Seed Co', array['Smoke Signals']::text[], 'boutique_breeder', 'United States', true, true),
    ('SoCal Seed Company', array[]::text[], 'seed_bank', 'United States', true, true),
    ('Southwest Seed Bank', array[]::text[], 'seed_bank', 'United States', true, true),
    ('The Seed Cellar', array['Seed Cellar']::text[], 'seed_bank', 'United States', true, true),
    ('The Seed Connection', array[]::text[], 'marketplace', 'United States', true, true),
    ('The Seed Source', array[]::text[], 'marketplace', null, true, true),
    ('The Seed Vault', array[]::text[], 'seed_bank', null, true, true),
    ('The Seedbank', array[]::text[], 'marketplace', null, true, true),
    ('United Cannabis Seeds', array[]::text[], 'marketplace', null, true, true),
    ('US Seed Bank', array['USA Seed Bank']::text[], 'seed_bank', 'United States', true, true),
    ('Vault Genetics', array[]::text[], 'breeder', null, true, true),
    ('West Coast Seed Bank', array['West Coast Seeds']::text[], 'seed_bank', 'United States', true, true),
    ('White Widow Seed Bank', array[]::text[], 'seed_bank', null, true, true),
    ('World Seed Supply', array[]::text[], 'marketplace', 'United States', true, true)
),
clean_rows as (
  select
    btrim(name) as name,
    coalesce((
      select array_agg(distinct btrim(alias) order by btrim(alias))
      from unnest(coalesce(aliases, array[]::text[])) as alias
      where btrim(alias) <> ''
        and lower(regexp_replace(btrim(alias), '\s+', ' ', 'g')) <> lower(regexp_replace(btrim(name), '\s+', ' ', 'g'))
    ), array[]::text[]) as aliases,
    coalesce(nullif(btrim(source_type), ''), 'other') as source_type,
    nullif(btrim(country), '') as country,
    coalesce(verified, false) as verified,
    coalesce(active, true) as active
  from seed_rows
  where btrim(name) <> ''
),
deduped_rows as (
  select distinct on (lower(regexp_replace(btrim(name), '\s+', ' ', 'g')))
    name,
    aliases,
    source_type,
    country,
    verified,
    active
  from clean_rows
  order by lower(regexp_replace(btrim(name), '\s+', ' ', 'g')), name
)
insert into public.source_directory (
  name,
  aliases,
  source_type,
  country,
  verified,
  active
)
select
  name,
  aliases,
  source_type,
  country,
  verified,
  active
from deduped_rows
on conflict (normalized_name) do update
set
  name = excluded.name,
  aliases = excluded.aliases,
  source_type = excluded.source_type,
  country = excluded.country,
  verified = excluded.verified,
  active = excluded.active,
  updated_at = now()
where public.source_directory.name is distinct from excluded.name
  or public.source_directory.aliases is distinct from excluded.aliases
  or public.source_directory.source_type is distinct from excluded.source_type
  or public.source_directory.country is distinct from excluded.country
  or public.source_directory.verified is distinct from excluded.verified
  or public.source_directory.active is distinct from excluded.active;
