-- Curated released Variety Directory expansion.
-- Seed-only migration: preserves existing rows and keeps custom variety workflow unchanged.
-- Low-confidence items intentionally not added:
-- - Poppin Fire catalog-specific releases were not added without a confirmed catalog reference.
-- - Wolfpack Selections catalog-specific releases were not added without a confirmed catalog reference.
-- - Additional Tiki Madman and Good Genetix catalog items beyond the explicitly requested or high-confidence releases were held for review.

with seed_values (
  name,
  aliases,
  source_name,
  variety_type,
  verified,
  active
) as (
  values
    ('Alaskan Purple', array[]::text[], 'Seedsman', 'cannabis', true, true),
    ('Peyote Wi-Fi', array['Peyote WiFi']::text[], 'Seedsman', 'cannabis', true, true),
    ('Purple Ghost Candy', array[]::text[], 'Seedsman', 'cannabis', true, true),
    ('Seedsman Haze', array[]::text[], 'Seedsman', 'cannabis', true, true),
    ('Strawberry Cheesecake Auto', array[]::text[], 'Seedsman', 'autoflower', true, true),
    ('24 Carat', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('3 Bears OG', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Alien vs. Triangle', array['Alien vs Triangle', 'AVT']::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('All Gas OG', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Animal Mints', array[]::text[], 'Seed Junky Genetics', 'cannabis', true, true),
    ('Apple Jax', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Apple Tartz', array[]::text[], 'Clearwater Genetics', 'cannabis', true, true),
    ('Apples & Bananas', array['Apples and Bananas']::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Apricot Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Aunt Ginny''s Elixir', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Auto Banana Blaze', array[]::text[], 'Dutch Passion', 'autoflower', true, true),
    ('Auto Cinderella Jack', array[]::text[], 'Dutch Passion', 'autoflower', true, true),
    ('Auto Daiquiri Lime', array[]::text[], 'Dutch Passion', 'autoflower', true, true),
    ('Auto Mazar', array[]::text[], 'Dutch Passion', 'autoflower', true, true),
    ('Auto Ultimate', array[]::text[], 'Dutch Passion', 'autoflower', true, true),
    ('Autumn Beauty Sunflower', array[]::text[], 'Botanical Interests', 'flower', true, true),
    ('Ayahuasca Purple', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Bahama Berry', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Bahama Mama', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Banana Hammock', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Banana Punch', array[]::text[], 'Symbiotic Genetics', 'cannabis', true, true),
    ('Banana Purple Punch Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Benary''s Giant Zinnia', array[]::text[], 'Johnny''s Selected Seeds', 'flower', true, true),
    ('Big Beef Tomato', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Big Detroit Energy', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Black Beauty Zucchini', array[]::text[], 'Ferry-Morse', 'vegetable', true, true),
    ('Black Krim Tomato', array[]::text[], 'Baker Creek Heirloom Seeds', 'vegetable', true, true),
    ('Black Magic', array[]::text[], 'Wizard Trees Genetics', 'cannabis', true, true),
    ('Black Seeded Simpson Lettuce', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Black Velvet', array[]::text[], 'Clearwater Genetics', 'cannabis', true, true),
    ('Blackberry Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Block Monster', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Bloomsdale Spinach', array[]::text[], 'Botanical Interests', 'vegetable', true, true),
    ('Blue Boy Bachelor''s Button', array[]::text[], 'Botanical Interests', 'flower', true, true),
    ('Blue Lake Bush Bean', array[]::text[], 'Ferry-Morse', 'vegetable', true, true),
    ('Blue Microverse', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Blue Razzsicle', array[]::text[], 'Clearwater Genetics', 'cannabis', true, true),
    ('Blue Slushie', array[]::text[], 'Raw Genetics', 'cannabis', true, true),
    ('Blue Sunset Sherbert', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Blueberry Pancakes', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Blunicorn', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Boston Pickling Cucumber', array[]::text[], 'Ferry-Morse', 'vegetable', true, true),
    ('Bouquet Dill', array[]::text[], 'Botanical Interests', 'herb', true, true),
    ('Brandywine Tomato', array[]::text[], 'Baker Creek Heirloom Seeds', 'vegetable', true, true),
    ('Bright Lights Cosmos', array[]::text[], 'Ferry-Morse', 'flower', true, true),
    ('Buttercrunch Lettuce', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Cake Crasher', array[]::text[], 'Seed Junky Genetics', 'cannabis', true, true),
    ('California Giant Zinnia', array[]::text[], 'Ferry-Morse', 'flower', true, true),
    ('California Octane', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('California Poppy', array[]::text[], 'Burpee', 'flower', true, true),
    ('California Wonder Pepper', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Caramel Cream', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Carpet of Snow Alyssum', array[]::text[], 'Ferry-Morse', 'ornamental', true, true),
    ('Chem Chillz', array[]::text[], 'Clearwater Genetics', 'cannabis', true, true),
    ('Cherokee Purple Tomato', array[]::text[], 'Baker Creek Heirloom Seeds', 'vegetable', true, true),
    ('Cherry Gar-see-ya', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Cherry Paloma', array[]::text[], 'Raw Genetics', 'cannabis', true, true),
    ('Chimera #3', array[]::text[], 'Beleaf', 'cannabis', true, true),
    ('Colonel Chem BX1', array[]::text[], 'Good Genetix', 'cannabis', true, true),
    ('Common Chives', array[]::text[], 'Burpee', 'herb', true, true),
    ('Cookies Kush', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Cosmic Queen', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Crackerjack Marigold', array[]::text[], 'Burpee', 'flower', true, true),
    ('Creamsizzle', array[]::text[], 'Clearwater Genetics', 'cannabis', true, true),
    ('Creme de la Chem', array['CDLC']::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Crescendo', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Crimson Sweet Watermelon', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Crystal Meth Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Cut and Come Again Zinnia', array[]::text[], 'Baker Creek Heirloom Seeds', 'flower', true, true),
    ('Dance World', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('Dante''s Inferno', array[]::text[], 'Clearwater Genetics', 'cannabis', true, true),
    ('Danvers 126 Carrot', array[]::text[], 'Botanical Interests', 'vegetable', true, true),
    ('Darth Chocolate Pancakes', array[]::text[], 'Wizard Trees Genetics', 'cannabis', true, true),
    ('Deluxe Sugar Cane', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Detroit Dark Red Beet', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Devil Driver', array[]::text[], 'Tiki Madman', 'cannabis', true, true),
    ('Dipz', array[]::text[], 'Beleaf', 'cannabis', true, true),
    ('Dos Si Dos 33', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Double Grape', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Dwarf Blue Curled Kale', array[]::text[], 'Ferry-Morse', 'vegetable', true, true),
    ('Early Girl Tomato', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Early Jalapeno Pepper', array[]::text[], 'Botanical Interests', 'vegetable', true, true),
    ('Early Lemon Berry', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Easy Bud', array[]::text[], 'Royal Queen Seeds', 'autoflower', true, true),
    ('El Chivo', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Empress of India Nasturtium', array[]::text[], 'Baker Creek Heirloom Seeds', 'ornamental', true, true),
    ('End Game', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('English Thyme', array[]::text[], 'Burpee', 'herb', true, true),
    ('Epsilon F1', array[]::text[], 'Royal Queen Seeds', 'autoflower', true, true),
    ('Ethos Cookies', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Euforia', array[]::text[], 'Dutch Passion', 'cannabis', true, true),
    ('Falcon 9', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('Fat Banana', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('First Class Funk', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Flap Jacks', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Forgotten Cookies', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Forum Stomper', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Frisian Dew', array[]::text[], 'Dutch Passion', 'cannabis', true, true),
    ('Frozen Grapes', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Fudgesicle', array[]::text[], 'Tiki Madman', 'cannabis', true, true),
    ('Fugue State', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Galaxy Brain', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Garlic Budder', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Garlic Sherb', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Gas Nana', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Gastro Pop', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Gazzurple', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Gelato Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Genovese Basil', array[]::text[], 'Botanical Interests', 'herb', true, true),
    ('Georgia Pie', array[]::text[], 'Seed Junky Genetics', 'cannabis', true, true),
    ('Glookies', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Glueberry OG', array[]::text[], 'Dutch Passion', 'cannabis', true, true),
    ('Golden Bantam Corn', array[]::text[], 'Baker Creek Heirloom Seeds', 'vegetable', true, true),
    ('Gorilla Cookies Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Gorilla Zkittlez', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Grandpa''s Cookies', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Grandpa''s Cookies #6', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Grandpa''s Cookies R1', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Granny Candy', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Grape Diamonds', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Grape Gasoline', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Grape Jubilee', array[]::text[], 'Raw Genetics', 'cannabis', true, true),
    ('Grease Monkey', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('Greek Oregano', array[]::text[], 'Botanical Interests', 'herb', true, true),
    ('Green Crack Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Green Zebra Tomato', array[]::text[], 'Johnny''s Selected Seeds', 'vegetable', true, true),
    ('Guava Root GMO', array[]::text[], 'Good Genetix', 'cannabis', true, true),
    ('Gummiez', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Habanero Orange Pepper', array[]::text[], 'Ferry-Morse', 'vegetable', true, true),
    ('Hale''s Best Jumbo Cantaloupe', array[]::text[], 'Baker Creek Heirloom Seeds', 'vegetable', true, true),
    ('Hella Jelly', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Hollands Hope', array['Holland''s Hope']::text[], 'Dutch Passion', 'cannabis', true, true),
    ('Honey Cream', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('Hood Candyz', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Hubbabubbahaze', array['HubbaBubbaHaze']::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('HulkBerry', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('Humboldt Dream', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Humboldt Headband', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Ice Cream Cake', array[]::text[], 'Seed Junky Genetics', 'cannabis', true, true),
    ('Italian Flat Leaf Parsley', array[]::text[], 'Burpee', 'herb', true, true),
    ('Italian Large Leaf Basil', array[]::text[], 'Burpee', 'herb', true, true),
    ('Jealousy', array[]::text[], 'Seed Junky Genetics', 'cannabis', true, true),
    ('Jelly Breath', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Jelly Donutz', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Jet Fuel Gelato', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Jewel Mix Nasturtium', array[]::text[], 'Botanical Interests', 'ornamental', true, true),
    ('Jimmy Nardello Pepper', array[]::text[], 'Baker Creek Heirloom Seeds', 'vegetable', true, true),
    ('Johnny Jump Up Viola', array[]::text[], 'Botanical Interests', 'ornamental', true, true),
    ('Jokerz', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Kentucky Wonder Pole Bean', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Kerosene Krash', array[]::text[], 'Dutch Passion', 'cannabis', true, true),
    ('Kimbo Kush', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('King Sherb', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Kobe', array[]::text[], 'Symbiotic Genetics', 'cannabis', true, true),
    ('Kush Mints', array[]::text[], 'Seed Junky Genetics', 'cannabis', true, true),
    ('LA Kush Cake', array[]::text[], 'Seed Junky Genetics', 'cannabis', true, true),
    ('Lacinato Kale', array[]::text[], 'Johnny''s Selected Seeds', 'vegetable', true, true),
    ('Lemon Cherry Soap', array[]::text[], 'Lit Farms', 'cannabis', true, true),
    ('Lemon Drip', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('Lemon Gem Marigold', array[]::text[], 'Botanical Interests', 'flower', true, true),
    ('Lemongrass', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Liberty Haze', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Lilac Diesel', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Lime OG', array[]::text[], 'Clearwater Genetics', 'cannabis', true, true),
    ('Lit Marker', array[]::text[], 'Lit Farms', 'cannabis', true, true),
    ('Litty', array[]::text[], 'Lit Farms', 'cannabis', true, true),
    ('LSD', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('LSD-25 Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Lung Buster', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Mad Dog', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Magic Melon', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Mai Tai #4', array[]::text[], 'Clearwater Genetics', 'cannabis', true, true),
    ('Mammoth Sunflower', array[]::text[], 'Burpee', 'flower', true, true),
    ('Mandarin Cookies', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Mandarin Zkittlez', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Mango Isle', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Mango Smile', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Marathon OG', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Marketmore 76 Cucumber', array[]::text[], 'Botanical Interests', 'vegetable', true, true),
    ('Medical Mass', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('Member Berry', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Mephisto''s Wedding', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Mexican Airlines Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Miami Mami', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Mike Larry', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('Milk and Qookies', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Milky Way F1', array[]::text[], 'Royal Queen Seeds', 'autoflower', true, true),
    ('Mimosa', array[]::text[], 'Symbiotic Genetics', 'cannabis', true, true),
    ('Mimosa x Orange Punch', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Mind Flayer', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Mint Chocolate Chip', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('Mortgage Lifter Tomato', array[]::text[], 'Baker Creek Heirloom Seeds', 'vegetable', true, true),
    ('Mountain Top Mint', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Orange Bud', array[]::text[], 'Dutch Passion', 'cannabis', true, true),
    ('Orange Creampop', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Orange Velvet Underground', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Orion F1', array[]::text[], 'Royal Queen Seeds', 'autoflower', true, true),
    ('Owl Pellet', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Pacific Beauty Calendula', array[]::text[], 'Botanical Interests', 'flower', true, true),
    ('Parris Island Cos Lettuce', array[]::text[], 'Baker Creek Heirloom Seeds', 'vegetable', true, true),
    ('Passion #1', array[]::text[], 'Dutch Passion', 'cannabis', true, true),
    ('Pave', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Pave Runtz', array[]::text[], 'Raw Genetics', 'cannabis', true, true),
    ('Peach Crescendo', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Permanent Marker', array[]::text[], 'Seed Junky Genetics', 'cannabis', true, true),
    ('Pineapple Chunk', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Pineapple Muffin', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Pink Panama', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Planet of the Grapes', array[]::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Platinum Garlic', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Platinum Kush Breath', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Poddy Mouth', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Popesicle', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Power Plant', array[]::text[], 'Dutch Passion', 'cannabis', true, true),
    ('Provider Bean', array[]::text[], 'Johnny''s Selected Seeds', 'vegetable', true, true),
    ('Purple Lemonade Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Queen''s Banner', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Quick One', array[]::text[], 'Royal Queen Seeds', 'autoflower', true, true),
    ('Rainbow Chip', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('Raspberry Parfait', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Rawtton Candy', array[]::text[], 'Raw Genetics', 'cannabis', true, true),
    ('Red Bullz', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Red Pop', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('Red Velvet Runtz', array[]::text[], 'Lit Farms', 'cannabis', true, true),
    ('Roma VF Tomato', array[]::text[], 'Ferry-Morse', 'vegetable', true, true),
    ('Route 65', array[]::text[], 'Wizard Trees Genetics', 'cannabis', true, true),
    ('Royal Carpet Alyssum', array[]::text[], 'Botanical Interests', 'ornamental', true, true),
    ('Royal Cheese', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('Royal Cookies', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('Royal Domina', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('Royal Dwarf', array[]::text[], 'Royal Queen Seeds', 'autoflower', true, true),
    ('Royal Gorilla', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('Royal Highness', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('RS11', array['Rainbow Sherbert #11']::text[], 'Wizard Trees Genetics', 'cannabis', true, true),
    ('Runtz Muffin', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Runtz S1', array[]::text[], 'Raw Genetics', 'cannabis', true, true),
    ('Samsquanch OG', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('San Marzano Tomato', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Scarlet Nantes Carrot', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Sensation Cosmos', array[]::text[], 'Botanical Interests', 'flower', true, true),
    ('Shaman', array[]::text[], 'Dutch Passion', 'cannabis', true, true),
    ('Shirazi', array[]::text[], 'Wizard Trees Genetics', 'cannabis', true, true),
    ('Shishito Pepper', array[]::text[], 'Johnny''s Selected Seeds', 'vegetable', true, true),
    ('Shogun', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('Silver Queen Corn', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Six Shooter Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Skywalker Haze', array[]::text[], 'Dutch Passion', 'cannabis', true, true),
    ('Slow Bolt Cilantro', array[]::text[], 'Ferry-Morse', 'herb', true, true),
    ('Slurricane', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Sour Crack', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Sour Stomper', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Special Queen #1', array[]::text[], 'Royal Queen Seeds', 'cannabis', true, true),
    ('Spotless Mind', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Squirt', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Straight Eight Cucumber', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Strawberries and Cream', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('Strawberry Gorilla Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('Strawberry Milk and Qookies', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Strawberry Nuggets', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Studio 54', array[]::text[], 'Wizard Trees Genetics', 'cannabis', true, true),
    ('Stuffed French Toast', array[]::text[], 'Raw Genetics', 'cannabis', true, true),
    ('Sugar Baby Watermelon', array[]::text[], 'Ferry-Morse', 'vegetable', true, true),
    ('Sugar Cane', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Sugar Snap Pea', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('Sun Gold Tomato', array[]::text[], 'Johnny''s Selected Seeds', 'vegetable', true, true),
    ('Swiss Giants Pansy', array[]::text[], 'Ferry-Morse', 'ornamental', true, true),
    ('Tangerine Dream', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Tea Time', array[]::text[], 'Wizard Trees Genetics', 'cannabis', true, true),
    ('Teddy Bear Sunflower', array[]::text[], 'Burpee', 'flower', true, true),
    ('Temptation', array[]::text[], 'Lit Farms', 'cannabis', true, true),
    ('Terpgasm', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Thai Basil', array[]::text[], 'Botanical Interests', 'herb', true, true),
    ('The Keeper', array[]::text[], 'Wizard Trees Genetics', 'cannabis', true, true),
    ('The Menthol', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('The Soap', array[]::text[], 'Seed Junky Genetics', 'cannabis', true, true),
    ('Think Different', array[]::text[], 'Dutch Passion', 'autoflower', true, true),
    ('Tigerz Eye', array[]::text[], 'Compound Genetics', 'cannabis', true, true),
    ('Tina', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('Titan F1', array[]::text[], 'Royal Queen Seeds', 'autoflower', true, true),
    ('Toaster Strudel', array[]::text[], 'Clearwater Genetics', 'cannabis', true, true),
    ('Toof Decay', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Triangle Mints', array[]::text[], 'Seed Junky Genetics', 'cannabis', true, true),
    ('Trichopath', array[]::text[], 'In House Genetics', 'cannabis', true, true),
    ('Truffle Treats', array[]::text[], 'Beleaf', 'cannabis', true, true),
    ('Udder Madness', array[]::text[], 'Solfire Gardens', 'cannabis', true, true),
    ('Vanilla Frosting', array[]::text[], 'Humboldt Seed Company', 'cannabis', true, true),
    ('Walter White', array[]::text[], 'Mephisto Genetics', 'autoflower', true, true),
    ('Waltham Butternut Squash', array[]::text[], 'Burpee', 'vegetable', true, true),
    ('WAP', array[]::text[], 'Lit Farms', 'cannabis', true, true),
    ('Warheads', array[]::text[], 'Lit Farms', 'cannabis', true, true),
    ('Watermelon Zkittlez', array[]::text[], 'Barney''s Farm', 'cannabis', true, true),
    ('Wedding Crasher', array[]::text[], 'Symbiotic Genetics', 'cannabis', true, true),
    ('Wedding Glue Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true),
    ('White Truffle', array[]::text[], 'Beleaf', 'cannabis', true, true),
    ('Wizard''s Apprentice', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Wonka Bars', array[]::text[], 'Exotic Genetix', 'cannabis', true, true),
    ('Zamaldelica Express', array[]::text[], 'Night Owl Seeds', 'autoflower', true, true),
    ('Zangria', array[]::text[], 'Wizard Trees Genetics', 'cannabis', true, true),
    ('Zero Gravity', array[]::text[], 'Clearwater Genetics', 'cannabis', true, true),
    ('Zoap', array[]::text[], 'Wizard Trees Genetics', 'cannabis', true, true),
    ('Zsweet Inzanity', array['Zsweet Insanity']::text[], 'Ethos Genetics', 'cannabis', true, true),
    ('Ztrawberriez Auto', array[]::text[], 'Fast Buds', 'autoflower', true, true)
), resolved_values as (
  select
    seed_values.name,
    seed_values.aliases,
    source_directory.id as source_id,
    nullif(seed_values.source_name, '') as source_name,
    seed_values.variety_type,
    seed_values.verified,
    seed_values.active
  from seed_values
  left join public.source_directory
    on source_directory.normalized_name = lower(regexp_replace(trim(seed_values.source_name), '\s+', ' ', 'g'))
)
insert into public.variety_directory (
  name,
  aliases,
  source_id,
  source_name,
  variety_type,
  verified,
  active
)
select
  name,
  aliases,
  source_id,
  source_name,
  variety_type,
  verified,
  active
from resolved_values
on conflict (normalized_name) do update
set
  aliases = (
    select coalesce(array_agg(alias_value order by alias_value), array[]::text[])
    from (
      select distinct btrim(alias_value) as alias_value
      from unnest(coalesce(public.variety_directory.aliases, array[]::text[]) || coalesce(excluded.aliases, array[]::text[])) as alias_values(alias_value)
      where btrim(alias_value) <> ''
        and lower(btrim(alias_value)) <> public.variety_directory.normalized_name
    ) deduped_aliases
  ),
  source_id = coalesce(public.variety_directory.source_id, excluded.source_id),
  source_name = coalesce(public.variety_directory.source_name, excluded.source_name),
  variety_type = case
    when coalesce(public.variety_directory.variety_type, '') in ('', 'unknown') then excluded.variety_type
    else public.variety_directory.variety_type
  end,
  verified = public.variety_directory.verified or excluded.verified,
  active = public.variety_directory.active,
  updated_at = now();

notify pgrst, 'reload schema';
