-- Initial curated Variety Directory seed for variety autocomplete.
-- Modest common-variety baseline; idempotent by generated normalized_name.

insert into public.variety_directory (
  name,
  aliases,
  variety_type,
  verified,
  active
)
values
  ('Acapulco Gold', array[]::text[], 'unknown', true, true),
  ('Afghan', array[]::text[], 'unknown', true, true),
  ('Afghani #1', array[]::text[], 'unknown', true, true),
  ('AK-47', array[]::text[], 'unknown', true, true),
  ('Alaskan Thunder Fuck', array['ATF']::text[], 'unknown', true, true),
  ('Amnesia', array[]::text[], 'unknown', true, true),
  ('Amnesia Haze', array[]::text[], 'unknown', true, true),
  ('Apple Fritter', array[]::text[], 'unknown', true, true),
  ('Bacio Gelato', array[]::text[], 'unknown', true, true),
  ('Banana Kush', array[]::text[], 'unknown', true, true),
  ('Banana OG', array[]::text[], 'unknown', true, true),
  ('Berry White', array[]::text[], 'unknown', true, true),
  ('Biscotti', array[]::text[], 'unknown', true, true),
  ('Black Afghan', array[]::text[], 'unknown', true, true),
  ('Black Cherry Gelato', array[]::text[], 'unknown', true, true),
  ('Black Cherry Punch', array[]::text[], 'unknown', true, true),
  ('Black Domina', array[]::text[], 'unknown', true, true),
  ('Black Jack', array[]::text[], 'unknown', true, true),
  ('Black Lime Reserve', array[]::text[], 'unknown', true, true),
  ('Blackberry Kush', array[]::text[], 'unknown', true, true),
  ('Blue Cheese', array[]::text[], 'unknown', true, true),
  ('Blue Cookies', array[]::text[], 'unknown', true, true),
  ('Blue Dream', array[]::text[], 'unknown', true, true),
  ('Blue Gelato', array[]::text[], 'unknown', true, true),
  ('Blue Haze', array[]::text[], 'unknown', true, true),
  ('Blue Magoo', array[]::text[], 'unknown', true, true),
  ('Blue Mystic', array[]::text[], 'unknown', true, true),
  ('Blueberry', array[]::text[], 'unknown', true, true),
  ('Blueberry Muffin', array[]::text[], 'unknown', true, true),
  ('Bruce Banner', array[]::text[], 'unknown', true, true),
  ('Bubba Kush', array[]::text[], 'unknown', true, true),
  ('Bubble Gum', array[]::text[], 'unknown', true, true),
  ('C99', array['Cinderella 99']::text[], 'unknown', true, true),
  ('Cereal Milk', array[]::text[], 'unknown', true, true),
  ('Chemdawg', array['Chemdog']::text[], 'unknown', true, true),
  ('Chem D', array['Chemdog D']::text[], 'unknown', true, true),
  ('Chem 91', array[]::text[], 'unknown', true, true),
  ('Cherry AK', array[]::text[], 'unknown', true, true),
  ('Cherry Pie', array[]::text[], 'unknown', true, true),
  ('Chocolope', array[]::text[], 'unknown', true, true),
  ('Cinex', array[]::text[], 'unknown', true, true),
  ('Cinderella 99', array[]::text[], 'unknown', true, true),
  ('Cookies and Cream', array[]::text[], 'unknown', true, true),
  ('Critical', array[]::text[], 'unknown', true, true),
  ('Critical Kush', array[]::text[], 'unknown', true, true),
  ('Critical Mass', array[]::text[], 'unknown', true, true),
  ('Death Star', array[]::text[], 'unknown', true, true),
  ('Do-Si-Dos', array['Dosidos', 'Do Si Dos']::text[], 'unknown', true, true),
  ('Dolato', array[]::text[], 'unknown', true, true),
  ('Durban Poison', array[]::text[], 'unknown', true, true),
  ('Dutch Treat', array[]::text[], 'unknown', true, true),
  ('East Coast Sour Diesel', array[]::text[], 'unknown', true, true),
  ('El Jefe', array[]::text[], 'unknown', true, true),
  ('Face Off OG', array[]::text[], 'unknown', true, true),
  ('Fire OG', array[]::text[], 'unknown', true, true),
  ('Forbidden Fruit', array[]::text[], 'unknown', true, true),
  ('G13', array[]::text[], 'unknown', true, true),
  ('Gelato', array[]::text[], 'unknown', true, true),
  ('Gelato #33', array[]::text[], 'unknown', true, true),
  ('Gelato #41', array[]::text[], 'unknown', true, true),
  ('Ghost OG', array[]::text[], 'unknown', true, true),
  ('Girl Scout Cookies', array['GSC']::text[], 'unknown', true, true),
  ('GMO Cookies', array['GMO']::text[], 'unknown', true, true),
  ('God Bud', array[]::text[], 'unknown', true, true),
  ('Golden Goat', array[]::text[], 'unknown', true, true),
  ('Granddaddy Purple', array[]::text[], 'unknown', true, true),
  ('Grape Ape', array[]::text[], 'unknown', true, true),
  ('Grape Pie', array[]::text[], 'unknown', true, true),
  ('Grape Stomper', array[]::text[], 'unknown', true, true),
  ('Grapefruit', array[]::text[], 'unknown', true, true),
  ('Green Crack', array[]::text[], 'unknown', true, true),
  ('Harlequin', array[]::text[], 'unknown', true, true),
  ('Headband', array[]::text[], 'unknown', true, true),
  ('Hindu Kush', array[]::text[], 'unknown', true, true),
  ('Ice Cream Cake', array[]::text[], 'unknown', true, true),
  ('Jack Herer', array[]::text[], 'unknown', true, true),
  ('Jack the Ripper', array[]::text[], 'unknown', true, true),
  ('Jillybean', array[]::text[], 'unknown', true, true),
  ('Kosher Kush', array[]::text[], 'unknown', true, true),
  ('LA Confidential', array[]::text[], 'unknown', true, true),
  ('Lamb''s Bread', array['Lamb''s Breath']::text[], 'unknown', true, true),
  ('Larry OG', array[]::text[], 'unknown', true, true),
  ('Lemon Cherry Gelato', array[]::text[], 'unknown', true, true),
  ('Lemon Haze', array[]::text[], 'unknown', true, true),
  ('Lemon Kush', array[]::text[], 'unknown', true, true),
  ('Lemon Skunk', array[]::text[], 'unknown', true, true),
  ('London Pound Cake', array[]::text[], 'unknown', true, true),
  ('MAC', array['Miracle Alien Cookies']::text[], 'unknown', true, true),
  ('Maui Wowie', array[]::text[], 'unknown', true, true),
  ('Mendo Breath', array[]::text[], 'unknown', true, true),
  ('Mimosa', array[]::text[], 'unknown', true, true),
  ('MK Ultra', array[]::text[], 'unknown', true, true),
  ('Motorbreath', array[]::text[], 'unknown', true, true),
  ('Northern Lights', array[]::text[], 'unknown', true, true),
  ('NYC Diesel', array[]::text[], 'unknown', true, true),
  ('OG Kush', array[]::text[], 'unknown', true, true),
  ('Orange Bud', array[]::text[], 'unknown', true, true),
  ('Orange Cookies', array[]::text[], 'unknown', true, true),
  ('Papaya', array[]::text[], 'unknown', true, true),
  ('Peanut Butter Breath', array[]::text[], 'unknown', true, true),
  ('Pineapple Chunk', array[]::text[], 'unknown', true, true),
  ('Pineapple Express', array[]::text[], 'unknown', true, true),
  ('Pink Kush', array[]::text[], 'unknown', true, true),
  ('Platinum Cookies', array[]::text[], 'unknown', true, true),
  ('Platinum OG', array[]::text[], 'unknown', true, true),
  ('Purple Haze', array[]::text[], 'unknown', true, true),
  ('Purple Kush', array[]::text[], 'unknown', true, true),
  ('Purple Punch', array[]::text[], 'unknown', true, true),
  ('Runtz', array[]::text[], 'unknown', true, true),
  ('SFV OG', array[]::text[], 'unknown', true, true),
  ('Sherbert', array[]::text[], 'unknown', true, true),
  ('Sherbet', array[]::text[], 'unknown', true, true),
  ('Silver Haze', array[]::text[], 'unknown', true, true),
  ('Skywalker OG', array[]::text[], 'unknown', true, true),
  ('Sour Diesel', array[]::text[], 'unknown', true, true),
  ('Sour Kush', array[]::text[], 'unknown', true, true),
  ('Sour Tangie', array[]::text[], 'unknown', true, true),
  ('Strawberry Banana', array[]::text[], 'unknown', true, true),
  ('Strawberry Cough', array[]::text[], 'unknown', true, true),
  ('Sunset Sherbet', array[]::text[], 'unknown', true, true),
  ('Super Lemon Haze', array[]::text[], 'unknown', true, true),
  ('Super Silver Haze', array[]::text[], 'unknown', true, true),
  ('Tahoe OG', array[]::text[], 'unknown', true, true),
  ('Tangie', array[]::text[], 'unknown', true, true),
  ('Trainwreck', array[]::text[], 'unknown', true, true),
  ('Triangle Kush', array[]::text[], 'unknown', true, true),
  ('Tropicana Cookies', array[]::text[], 'unknown', true, true),
  ('UK Cheese', array['Cheese']::text[], 'unknown', true, true),
  ('Wedding Cake', array['Triangle Mints #23']::text[], 'unknown', true, true),
  ('White Fire OG', array['WiFi OG']::text[], 'unknown', true, true),
  ('White Rhino', array[]::text[], 'unknown', true, true),
  ('White Widow', array[]::text[], 'unknown', true, true),
  ('WiFi OG', array['White Fire OG']::text[], 'unknown', true, true),
  ('Zkittlez', array['Skittles']::text[], 'unknown', true, true),
  ('Alien OG', array[]::text[], 'unknown', true, true),
  ('Alien Rock Candy', array[]::text[], 'unknown', true, true),
  ('Animal Cookies', array[]::text[], 'unknown', true, true),
  ('Animal Face', array[]::text[], 'unknown', true, true),
  ('Animal Mints', array[]::text[], 'unknown', true, true),
  ('Apples and Bananas', array[]::text[], 'unknown', true, true),
  ('Banana Cream', array[]::text[], 'unknown', true, true),
  ('Banana Punch', array[]::text[], 'unknown', true, true),
  ('Bananaconda', array[]::text[], 'unknown', true, true),
  ('Big Bud', array[]::text[], 'unknown', true, true),
  ('Birthday Cake', array[]::text[], 'unknown', true, true),
  ('Black Runtz', array[]::text[], 'unknown', true, true),
  ('Blue Walker', array[]::text[], 'unknown', true, true),
  ('Blue Zkittlez', array[]::text[], 'unknown', true, true),
  ('Bubba Fett', array[]::text[], 'unknown', true, true),
  ('Cake Crasher', array[]::text[], 'unknown', true, true),
  ('Candyland', array[]::text[], 'unknown', true, true),
  ('Cap Junky', array[]::text[], 'unknown', true, true),
  ('Chem Cookies', array[]::text[], 'unknown', true, true),
  ('Cherry Cookies', array[]::text[], 'unknown', true, true),
  ('Cherry Garcia', array[]::text[], 'unknown', true, true),
  ('Cherry Limeade', array[]::text[], 'unknown', true, true),
  ('Chocolate Thai', array[]::text[], 'unknown', true, true),
  ('Cookies Gelato', array[]::text[], 'unknown', true, true),
  ('Critical Jack', array[]::text[], 'unknown', true, true),
  ('Donkey Butter', array[]::text[], 'unknown', true, true),
  ('Dosidos #22', array[]::text[], 'unknown', true, true),
  ('Dragon Fruit', array[]::text[], 'unknown', true, true),
  ('Dream Queen', array[]::text[], 'unknown', true, true),
  ('Durban Cookies', array[]::text[], 'unknown', true, true),
  ('Ecto Cooler', array[]::text[], 'unknown', true, true),
  ('Forbidden Runtz', array[]::text[], 'unknown', true, true),
  ('French Cookies', array[]::text[], 'unknown', true, true),
  ('Frosted Gelato', array[]::text[], 'unknown', true, true),
  ('Gary Payton', array[]::text[], 'unknown', true, true),
  ('Gelonade', array[]::text[], 'unknown', true, true),
  ('Georgia Pie', array[]::text[], 'unknown', true, true),
  ('GMO Rootbeer', array[]::text[], 'unknown', true, true),
  ('Golden Pineapple', array[]::text[], 'unknown', true, true),
  ('Gorilla Glue #4', array['GG4', 'Original Glue']::text[], 'unknown', true, true),
  ('Grape Gas', array[]::text[], 'unknown', true, true),
  ('Grape God', array[]::text[], 'unknown', true, true),
  ('Grape Kush', array[]::text[], 'unknown', true, true),
  ('Grape Sorbet', array[]::text[], 'unknown', true, true),
  ('Grape Zkittlez', array[]::text[], 'unknown', true, true),
  ('Grapes and Cream', array[]::text[], 'unknown', true, true),
  ('Grease Monkey', array[]::text[], 'unknown', true, true),
  ('Guava', array[]::text[], 'unknown', true, true),
  ('Gushers', array[]::text[], 'unknown', true, true),
  ('Hash Plant', array[]::text[], 'unknown', true, true),
  ('Hawaiian Snow', array[]::text[], 'unknown', true, true),
  ('Hell''s OG', array[]::text[], 'unknown', true, true),
  ('Horchata', array[]::text[], 'unknown', true, true),
  ('J1', array[]::text[], 'unknown', true, true),
  ('Jealousy', array[]::text[], 'unknown', true, true),
  ('Jungle Cake', array[]::text[], 'unknown', true, true),
  ('Khalifa Kush', array[]::text[], 'unknown', true, true),
  ('King Louis XIII', array[]::text[], 'unknown', true, true),
  ('Kush Mints', array[]::text[], 'unknown', true, true),
  ('Lava Cake', array[]::text[], 'unknown', true, true),
  ('Layer Cake', array[]::text[], 'unknown', true, true),
  ('Lemon Cake', array[]::text[], 'unknown', true, true),
  ('Lemon Tree', array[]::text[], 'unknown', true, true),
  ('Lemonade', array[]::text[], 'unknown', true, true),
  ('Liberty Haze', array[]::text[], 'unknown', true, true),
  ('London Pound Mints', array[]::text[], 'unknown', true, true),
  ('Mandarin Cookies', array[]::text[], 'unknown', true, true),
  ('Mango Haze', array[]::text[], 'unknown', true, true),
  ('Marathon OG', array[]::text[], 'unknown', true, true),
  ('Member Berry', array[]::text[], 'unknown', true, true),
  ('Milk and Cookies', array[]::text[], 'unknown', true, true),
  ('Mint Chocolate Chip', array[]::text[], 'unknown', true, true),
  ('Mochi', array[]::text[], 'unknown', true, true),
  ('Motorbreath #15', array[]::text[], 'unknown', true, true),
  ('Mr. Nice', array[]::text[], 'unknown', true, true),
  ('Neville''s Haze', array[]::text[], 'unknown', true, true),
  ('Nutter Butter', array[]::text[], 'unknown', true, true),
  ('Obama Kush', array[]::text[], 'unknown', true, true),
  ('Oreoz', array[]::text[], 'unknown', true, true),
  ('Papaya Punch', array[]::text[], 'unknown', true, true),
  ('Paris OG', array[]::text[], 'unknown', true, true),
  ('Peaches and Cream', array[]::text[], 'unknown', true, true),
  ('Permanent Marker', array[]::text[], 'unknown', true, true),
  ('Pineapple Upside Down Cake', array[]::text[], 'unknown', true, true),
  ('Pink Cookies', array[]::text[], 'unknown', true, true),
  ('Platinum Bubba Kush', array[]::text[], 'unknown', true, true),
  ('Platinum Kush', array[]::text[], 'unknown', true, true),
  ('Purple Chem', array[]::text[], 'unknown', true, true),
  ('Purple Diesel', array[]::text[], 'unknown', true, true),
  ('Purple Dream', array[]::text[], 'unknown', true, true),
  ('Purple Urkle', array[]::text[], 'unknown', true, true),
  ('Rainbow Belts', array[]::text[], 'unknown', true, true),
  ('Rainbow Sherbet', array[]::text[], 'unknown', true, true),
  ('Red Congolese', array[]::text[], 'unknown', true, true),
  ('Romulan', array[]::text[], 'unknown', true, true),
  ('Rosetta Stone', array[]::text[], 'unknown', true, true),
  ('RS11', array[]::text[], 'unknown', true, true),
  ('Sage N Sour', array[]::text[], 'unknown', true, true),
  ('Scooby Snacks', array[]::text[], 'unknown', true, true),
  ('Secret Cookies', array[]::text[], 'unknown', true, true),
  ('Sherbacio', array[]::text[], 'unknown', true, true),
  ('Slurricane', array[]::text[], 'unknown', true, true),
  ('Snowman', array[]::text[], 'unknown', true, true),
  ('Sour Apple', array[]::text[], 'unknown', true, true),
  ('Sour Banana Sherbet', array[]::text[], 'unknown', true, true),
  ('Sour Bubble', array[]::text[], 'unknown', true, true),
  ('Sour Cherry', array[]::text[], 'unknown', true, true),
  ('Space Queen', array[]::text[], 'unknown', true, true),
  ('Strawnana', array[]::text[], 'unknown', true, true),
  ('Sugar Black Rose', array[]::text[], 'unknown', true, true),
  ('Super Boof', array[]::text[], 'unknown', true, true),
  ('Super Glue', array[]::text[], 'unknown', true, true),
  ('Super Skunk', array[]::text[], 'unknown', true, true),
  ('Sweet Tooth', array[]::text[], 'unknown', true, true),
  ('Tahoe Cookies', array[]::text[], 'unknown', true, true),
  ('Tangie Cookies', array[]::text[], 'unknown', true, true),
  ('The White', array[]::text[], 'unknown', true, true),
  ('Thin Mint GSC', array[]::text[], 'unknown', true, true),
  ('Tiramisu', array[]::text[], 'unknown', true, true),
  ('Trop Cherry', array[]::text[], 'unknown', true, true),
  ('Tropical Runtz', array[]::text[], 'unknown', true, true),
  ('Vanilla Frosting', array[]::text[], 'unknown', true, true),
  ('Watermelon Zkittlez', array[]::text[], 'unknown', true, true),
  ('Wedding Crasher', array[]::text[], 'unknown', true, true),
  ('Wedding Pie', array[]::text[], 'unknown', true, true),
  ('White Cookies', array[]::text[], 'unknown', true, true),
  ('White Runtz', array[]::text[], 'unknown', true, true),
  ('White Tahoe Cookies', array[]::text[], 'unknown', true, true),
  ('Wonka Bars', array[]::text[], 'unknown', true, true),
  ('Yoda OG', array[]::text[], 'unknown', true, true),
  ('Zookies', array[]::text[], 'unknown', true, true),
  ('24k Gold', array[]::text[], 'unknown', true, true),
  ('3 Kings', array[]::text[], 'unknown', true, true),
  ('9 Pound Hammer', array[]::text[], 'unknown', true, true),
  ('Agent Orange', array[]::text[], 'unknown', true, true),
  ('Banana Split', array[]::text[], 'unknown', true, true),
  ('Blueberry Cookies', array[]::text[], 'unknown', true, true),
  ('Blueberry Headband', array[]::text[], 'unknown', true, true),
  ('Blueberry Kush', array[]::text[], 'unknown', true, true),
  ('Bubba Cookies', array[]::text[], 'unknown', true, true),
  ('Chem 4', array[]::text[], 'unknown', true, true),
  ('Cherry Bomb', array[]::text[], 'unknown', true, true),
  ('Chiquita Banana', array[]::text[], 'unknown', true, true),
  ('Critical Plus', array[]::text[], 'unknown', true, true),
  ('Double Dream', array[]::text[], 'unknown', true, true),
  ('Dutch Dragon', array[]::text[], 'unknown', true, true),
  ('Emerald Jack', array[]::text[], 'unknown', true, true),
  ('Fire Alien Kush', array[]::text[], 'unknown', true, true),
  ('Flo', array[]::text[], 'unknown', true, true),
  ('Gelato Cake', array[]::text[], 'unknown', true, true),
  ('Golden Lemons', array[]::text[], 'unknown', true, true),
  ('Grandpa''s Breath', array[]::text[], 'unknown', true, true),
  ('Green Gelato', array[]::text[], 'unknown', true, true),
  ('Haze', array[]::text[], 'unknown', true, true),
  ('Jack Flash', array[]::text[], 'unknown', true, true),
  ('Juicy Fruit', array[]::text[], 'unknown', true, true),
  ('Kandy Kush', array[]::text[], 'unknown', true, true),
  ('Killer Queen', array[]::text[], 'unknown', true, true),
  ('King''s Kush', array[]::text[], 'unknown', true, true),
  ('Lemon OG', array[]::text[], 'unknown', true, true),
  ('Mango Kush', array[]::text[], 'unknown', true, true),
  ('Master Kush', array[]::text[], 'unknown', true, true),
  ('Mazar', array[]::text[], 'unknown', true, true),
  ('Mother''s Milk', array[]::text[], 'unknown', true, true),
  ('Nuken', array[]::text[], 'unknown', true, true),
  ('Orange Creamsicle', array[]::text[], 'unknown', true, true),
  ('Orange Sherbet', array[]::text[], 'unknown', true, true),
  ('Pennywise', array[]::text[], 'unknown', true, true),
  ('Pineapple Kush', array[]::text[], 'unknown', true, true),
  ('Purple Afghani', array[]::text[], 'unknown', true, true),
  ('Purple Trainwreck', array[]::text[], 'unknown', true, true),
  ('Quantum Kush', array[]::text[], 'unknown', true, true),
  ('Sensi Star', array[]::text[], 'unknown', true, true),
  ('Shishkaberry', array[]::text[], 'unknown', true, true),
  ('Skunk #1', array[]::text[], 'unknown', true, true),
  ('Somango', array[]::text[], 'unknown', true, true),
  ('Sour OG', array[]::text[], 'unknown', true, true),
  ('Strawberry Diesel', array[]::text[], 'unknown', true, true),
  ('Super Sour Diesel', array[]::text[], 'unknown', true, true),
  ('Sweet Island Skunk', array[]::text[], 'unknown', true, true),
  ('Tahoe Alien', array[]::text[], 'unknown', true, true),
  ('Tangilope', array[]::text[], 'unknown', true, true),
  ('Vanilla Kush', array[]::text[], 'unknown', true, true),
  ('White Russian', array[]::text[], 'unknown', true, true)
on conflict (normalized_name) do update
set
  aliases = (
    select coalesce(array_agg(alias_value order by alias_value), array[]::text[])
    from (
      select distinct btrim(alias_value) as alias_value
      from unnest(coalesce(public.variety_directory.aliases, array[]::text[]) || coalesce(excluded.aliases, array[]::text[])) as alias_values(alias_value)
      where btrim(alias_value) <> ''
    ) deduped_aliases
  ),
  variety_type = excluded.variety_type,
  verified = public.variety_directory.verified or excluded.verified,
  active = true,
  updated_at = now();

notify pgrst, 'reload schema';
