-- Initial Source Directory seed for source autocomplete.
-- Idempotent: generated normalized_name handles conflict matching.

insert into public.source_directory (
  name,
  aliases,
  source_type,
  country,
  verified,
  active
)
values
  ('Private Breeder', array[]::text[], 'fallback', null, false, true),
  ('Friend / Trade', array['Friend Trade', 'Trade']::text[], 'fallback', null, false, true),
  ('Self Produced', array['Self-Produced', 'Home Produced', 'Own Seeds']::text[], 'fallback', null, false, true),
  ('Unknown Source', array['Unknown']::text[], 'fallback', null, false, true),
  ('Other', array['Other Source']::text[], 'fallback', null, false, true),
  ('Wizard Trees Genetics', array['Wizard Trees', 'Wizard Trees Genetics']::text[], 'breeder', 'US', true, true),
  ('Archive Seed Bank', array['Archive Seeds', 'Archive']::text[], 'breeder', 'US', true, true),
  ('Compound Genetics', array['Compound']::text[], 'breeder', 'US', true, true),
  ('Seed Junky Genetics', array['Seed Junky', 'Seed Junkies']::text[], 'breeder', 'US', true, true),
  ('Cannarado Genetics', array['Cannarado']::text[], 'breeder', 'US', true, true),
  ('Exotic Genetix', array['Exotic Genetics']::text[], 'breeder', 'US', true, true),
  ('Ethos Genetics', array['Ethos']::text[], 'breeder', 'US', true, true),
  ('DNA Genetics', array['DNA']::text[], 'breeder', 'NL', true, true),
  ('Reserva Privada', array['RP']::text[], 'breeder', 'NL', true, true),
  ('Barney''s Farm', array['Barneys Farm', 'Barney Farm']::text[], 'breeder', 'NL', true, true),
  ('Dutch Passion', array['Dutch Passion Seeds']::text[], 'breeder', 'NL', true, true),
  ('Sensi Seeds', array['Sensi']::text[], 'seed_bank', 'NL', true, true),
  ('Green House Seed Co.', array['Green House Seeds', 'Greenhouse Seeds', 'GHSC']::text[], 'breeder', 'NL', true, true),
  ('Royal Queen Seeds', array['RQS']::text[], 'seed_bank', 'ES', true, true),
  ('Sweet Seeds', array['Sweet Seeds Bank']::text[], 'breeder', 'ES', true, true),
  ('ACE Seeds', array['ACE']::text[], 'breeder', 'ES', true, true),
  ('Humboldt Seed Company', array['HSC', 'Humboldt Seed Co']::text[], 'breeder', 'US', true, true),
  ('Humboldt Seed Organization', array['HSO']::text[], 'breeder', 'ES', true, true),
  ('Mephisto Genetics', array['Mephisto']::text[], 'autoflower_breeder', 'ES', true, true),
  ('Night Owl Seeds', array['Night Owl']::text[], 'autoflower_breeder', 'US', true, true),
  ('Fast Buds', array['420 Fast Buds', 'FastBuds']::text[], 'autoflower_breeder', 'ES', true, true),
  ('Speedrun Seeds', array['Speedrun']::text[], 'autoflower_breeder', 'US', true, true),
  ('Atlas Seed', array['Atlas Seeds']::text[], 'breeder', 'US', true, true),
  ('Twenty20 Mendocino', array['Twenty20', '20Twenty Mendocino']::text[], 'breeder', 'US', true, true),
  ('Brothers Grimm Seeds', array['Brothers Grimm']::text[], 'breeder', 'US', true, true),
  ('Serious Seeds', array['Serious']::text[], 'breeder', 'NL', true, true),
  ('Mr. Nice Seedbank', array['Mr Nice Seeds', 'Mr. Nice Seeds']::text[], 'breeder', 'NL', true, true),
  ('T.H.Seeds', array['TH Seeds', 'T H Seeds']::text[], 'breeder', 'NL', true, true),
  ('Paradise Seeds', array['Paradise']::text[], 'breeder', 'NL', true, true),
  ('Nirvana Seeds', array['Nirvana']::text[], 'seed_bank', 'NL', true, true),
  ('Homegrown Cannabis Co.', array['Homegrown Cannabis Co', 'Homegrown Cannabis']::text[], 'seed_bank', 'US', true, true),
  ('Seedsman', array['Seedsman Seeds']::text[], 'marketplace', 'UK', true, true),
  ('North Atlantic Seed Co.', array['North Atlantic Seed Company', 'NASC']::text[], 'marketplace', 'US', true, true),
  ('Multiverse Beans', array['Multiverse', 'MVB']::text[], 'marketplace', 'US', true, true),
  ('Neptune Seed Bank', array['Neptune Seeds']::text[], 'marketplace', 'US', true, true),
  ('Great Lakes Genetics', array['GLG']::text[], 'marketplace', 'US', true, true),
  ('DC Seed Exchange', array['DCSE']::text[], 'marketplace', 'US', true, true),
  ('Seeds Here Now', array['SHN']::text[], 'marketplace', 'US', true, true),
  ('Oregon Elite Seeds', array['Oregon Elite']::text[], 'marketplace', 'US', true, true),
  ('JBC Seeds', array['JBC Seedbank']::text[], 'marketplace', 'US', true, true),
  ('Terpy Seeds', array['Terpy']::text[], 'marketplace', 'US', true, true),
  ('Speakeasy Seedbank', array['Speakeasy Seeds']::text[], 'marketplace', 'US', true, true),
  ('Attitude Seedbank', array['The Attitude Seedbank', 'Attitude Seeds']::text[], 'marketplace', 'UK', true, true),
  ('Herbies Seeds', array['Herbies Head Shop']::text[], 'marketplace', 'ES', true, true),
  ('MSNL', array['Marijuana Seeds NL']::text[], 'seed_bank', 'UK', true, true),
  ('Crop King Seeds', array['Crop King']::text[], 'seed_bank', 'CA', true, true),
  ('Quebec Cannabis Seeds', array['QCS']::text[], 'seed_bank', 'CA', true, true),
  ('True North Seed Bank', array['True North']::text[], 'marketplace', 'CA', true, true),
  ('Jordan of the Islands', array['JOTI']::text[], 'breeder', 'CA', true, true),
  ('Next Generation Seed Company', array['Next Generation Seeds']::text[], 'breeder', 'CA', true, true),
  ('Dr. Seeds', array['Dr Seeds']::text[], 'seed_bank', 'CA', true, true),
  ('Canuk Seeds', array['Canuk']::text[], 'seed_bank', 'CA', true, true),
  ('7 East Genetics', array['Seven East Genetics']::text[], 'breeder', 'CA', true, true),
  ('White Buffalo Seed Collective', array['White Buffalo']::text[], 'collective', 'CA', true, true),
  ('Jinxproof Genetics', array['Jinxproof']::text[], 'breeder', 'US', true, true),
  ('Bodhi Seeds', array['Bodhi']::text[], 'breeder', 'US', true, true),
  ('CSI Humboldt', array['CSI Humboldt Seeds', 'Csi Humboldt']::text[], 'breeder', 'US', true, true),
  ('Karma Genetics', array['Karma']::text[], 'breeder', 'NL', true, true),
  ('Solfire Gardens', array['Solfire']::text[], 'breeder', 'US', true, true),
  ('In House Genetics', array['In-House Genetics', 'IHG']::text[], 'breeder', 'US', true, true),
  ('Bloom Seed Co.', array['Bloom Seed Co', 'Bloom Seeds']::text[], 'breeder', 'US', true, true),
  ('Relentless Genetics', array['Relentless']::text[], 'breeder', 'US', true, true),
  ('Capulator', array['Capulator Seeds', 'Cap']::text[], 'breeder', 'US', true, true),
  ('Masonic Seed Co.', array['Masonic Seeds', 'Masonic Smoker']::text[], 'breeder', 'US', true, true),
  ('Dark Horse Genetics', array['Dark Horse']::text[], 'breeder', 'US', true, true),
  ('Rare Dankness', array['Rare Dankness Seeds']::text[], 'breeder', 'US', true, true),
  ('Boneyard Seeds Norcal', array['Boneyard Seeds']::text[], 'breeder', 'US', true, true),
  ('707 Seed Bank', array['707 Seeds']::text[], 'breeder', 'US', true, true),
  ('Mendo Dope Seeds', array['Mendo Dope']::text[], 'breeder', 'US', true, true),
  ('Mass Medical Strains', array['Mass Medical']::text[], 'breeder', 'US', true, true),
  ('Tonygreen''s Tortured Beans', array['Tonygreens Tortured Beans', 'Tony Green']::text[], 'breeder', 'US', true, true),
  ('Skunk House Genetics', array['Skunk House']::text[], 'breeder', 'US', true, true),
  ('Dungeon Vault Genetics', array['DVG']::text[], 'breeder', 'US', true, true),
  ('Sin City Seeds', array['Sin City']::text[], 'breeder', 'US', true, true),
  ('Cali Connection', array['The Cali Connection']::text[], 'breeder', 'US', true, true),
  ('DNA Crockett Family Farms', array['Crockett Family Farms', 'Crockett']::text[], 'breeder', 'US', true, true),
  ('Swamp Boys Seeds', array['Swamp Boys']::text[], 'breeder', 'US', true, true),
  ('Crane City Cannabis', array['Crane City']::text[], 'breeder', 'US', true, true),
  ('LIT Farms', array['Lit Farms']::text[], 'breeder', 'US', true, true),
  ('Clearwater Genetics', array['Clearwater']::text[], 'breeder', 'US', true, true),
  ('Solfire Genetics', array['Solfire Genetics']::text[], 'breeder', 'US', true, true),
  ('Umami Seed Co.', array['Umami Seeds', 'Umami']::text[], 'breeder', 'US', true, true),
  ('Seed Canary', array['Seed Canary']::text[], 'marketplace', 'US', true, true),
  ('Brothers in Farms', array['BIF Beans']::text[], 'breeder', 'US', false, true),
  ('Freeborn Selections', array['Freeborn']::text[], 'breeder', 'US', true, true),
  ('Mean Gene From Mendocino', array['Mean Gene', 'Mendocino Mean Gene']::text[], 'breeder', 'US', true, true),
  ('Riot Seeds', array['Riot']::text[], 'breeder', 'US', true, true),
  ('Raw Genetics', array['Raw Genetics Seeds']::text[], 'breeder', 'US', true, true),
  ('Square One Genetics', array['Square One']::text[], 'breeder', 'US', true, true),
  ('Robin Hood Seeds', array['Robin Hood']::text[], 'breeder', 'US', true, true),
  ('Lovin'' in Her Eyes', array['LIT Her Eyes', 'Lovin in Her Eyes']::text[], 'breeder', 'US', true, true),
  ('Mosca Seeds', array['Mosca']::text[], 'breeder', 'US', true, true),
  ('Second Generation Genetics', array['2nd Generation Genetics']::text[], 'breeder', 'US', true, true),
  ('Dungeons Vault Genetics', array['Dungeon Vault']::text[], 'breeder', 'US', true, true),
  ('AK Bean Brains', array['AKBB']::text[], 'breeder', 'US', true, true),
  ('NorStar Genetics', array['Norstar']::text[], 'breeder', 'US', true, true),
  ('SnowHigh Seeds', array['SnowHigh']::text[], 'breeder', 'US', true, true),
  ('Covert Genetics', array['Covert']::text[], 'breeder', 'US', false, true),
  ('Deeply Rooted Seed Bank', array['Deeply Rooted']::text[], 'marketplace', 'US', true, true),
  ('Hembra Genetics', array['Hembra']::text[], 'marketplace', 'US', true, true),
  ('Breeders Direct Seed Co.', array['Breeders Direct']::text[], 'marketplace', 'US', true, true),
  ('Seeds For Me', array['Seedsforme']::text[], 'marketplace', 'US', true, true),
  ('Well Grown Seeds', array['Well Grown']::text[], 'marketplace', 'US', true, true),
  ('Area 51 Seed Bank', array['Area 51 Seeds']::text[], 'marketplace', 'US', true, true),
  ('United Seed Bank', array['United Seeds']::text[], 'marketplace', 'US', true, true),
  ('Brotanical Gardens', array['Brotanical']::text[], 'marketplace', 'US', true, true),
  ('Insane Seeds', array['Insane Seed Posse']::text[], 'marketplace', 'US', true, true),
  ('Platinum Seed Bank', array['Platinum Seeds']::text[], 'marketplace', 'US', true, true),
  ('The Seed Source', array['Seed Source']::text[], 'marketplace', 'US', true, true),
  ('Seeds of Love', array['Seeds Of Love']::text[], 'marketplace', 'US', false, true),
  ('Pacific Seed Bank', array['Pacific Seeds']::text[], 'marketplace', 'US', true, true),
  ('ILGM', array['I Love Growing Marijuana']::text[], 'seed_bank', 'US', true, true),
  ('Growers Choice Seeds', array['Growers Choice']::text[], 'seed_bank', 'US', true, true),
  ('Premium Cultivars', array['Premium Cultivars Seeds']::text[], 'seed_bank', 'US', true, true),
  ('Sunwest Genetics', array['Sun West Genetics']::text[], 'seed_bank', 'CA', true, true),
  ('Sonoma Seeds', array['Sonoma']::text[], 'seed_bank', 'CA', true, true),
  ('Vancouver Seed Bank', array['VSB']::text[], 'seed_bank', 'CA', true, true),
  ('BC Bud Depot', array['BCBD']::text[], 'breeder', 'CA', true, true),
  ('Peak Seeds BC', array['Peak Seeds']::text[], 'breeder', 'CA', true, true),
  ('House of the Great Gardener', array['Great Gardener']::text[], 'breeder', 'CA', true, true),
  ('Reeferman Seeds', array['Reeferman']::text[], 'breeder', 'CA', true, true),
  ('Freedom of Seeds', array['Freedom Seeds']::text[], 'breeder', 'UK', true, true),
  ('Big Buddha Seeds', array['Big Buddha']::text[], 'breeder', 'UK', true, true),
  ('UGORG', array['Underground Originals']::text[], 'breeder', 'UK', true, true),
  ('Connoisseur Genetics', array['Connoisseur']::text[], 'breeder', 'UK', true, true),
  ('Real Seed Company', array['The Real Seed Company', 'RSC']::text[], 'seed_bank', 'UK', true, true),
  ('Real Gorilla Seeds', array['RGS']::text[], 'seed_bank', 'UK', true, true),
  ('Female Seeds', array['Female Seeds NL']::text[], 'breeder', 'NL', true, true),
  ('Amsterdam Genetics', array['Amsterdam Genetics Seeds']::text[], 'breeder', 'NL', true, true),
  ('Amsterdam Seed Center', array['ASC']::text[], 'marketplace', 'NL', true, true),
  ('Spliff Seeds', array['Spliff']::text[], 'breeder', 'NL', true, true),
  ('Ministry of Cannabis', array['MOC']::text[], 'breeder', 'NL', true, true),
  ('White Label Seeds', array['White Label']::text[], 'seed_bank', 'NL', true, true),
  ('Flying Dutchmen', array['The Flying Dutchmen']::text[], 'breeder', 'NL', true, true),
  ('KC Brains', array['KC Brains Holland']::text[], 'breeder', 'NL', true, true),
  ('Sagarmatha Seeds', array['Sagarmatha']::text[], 'breeder', 'NL', true, true),
  ('Serious Happiness Seeds', array['Serious Happiness']::text[], 'breeder', 'NL', false, true),
  ('Dinafem Seeds', array['Dinafem']::text[], 'legacy_breeder', 'ES', true, true),
  ('Kannabia Seeds', array['Kannabia']::text[], 'breeder', 'ES', true, true),
  ('Pyramid Seeds', array['Pyramid']::text[], 'breeder', 'ES', true, true),
  ('Medical Seeds', array['Medical Seeds Co']::text[], 'breeder', 'ES', true, true),
  ('Delicious Seeds', array['Delicious']::text[], 'breeder', 'ES', true, true),
  ('Philosopher Seeds', array['Philosopher']::text[], 'breeder', 'ES', true, true),
  ('Positronics Seeds', array['Positronics']::text[], 'breeder', 'ES', true, true),
  ('Reggae Seeds', array['Reggae']::text[], 'breeder', 'ES', true, true),
  ('Advanced Seeds', array['Advanced']::text[], 'breeder', 'ES', true, true),
  ('Gea Seeds', array['GEA Seeds']::text[], 'breeder', 'ES', true, true),
  ('World of Seeds', array['WOS']::text[], 'breeder', 'ES', true, true),
  ('Eva Seeds', array['Eva Female Seeds']::text[], 'breeder', 'ES', true, true),
  ('Original Sensible Seeds', array['Sensible Seeds']::text[], 'seed_bank', 'ES', true, true),
  ('Linda Seeds', array['Linda Semilla']::text[], 'seed_bank', 'ES', true, true),
  ('Seedstockers', array['Seed Stockers']::text[], 'breeder', 'ES', true, true),
  ('Ripper Seeds', array['Ripper']::text[], 'breeder', 'ES', true, true),
  ('Anesia Seeds', array['Anesia']::text[], 'breeder', 'ES', true, true),
  ('Zamnesia Seeds', array['Zamnesia']::text[], 'marketplace', 'NL', true, true),
  ('Dutch Headshop', array['Dutch-Headshop']::text[], 'marketplace', 'NL', true, true),
  ('Oaseeds', array['OA Seeds']::text[], 'marketplace', 'ES', true, true),
  ('Seeds Mafia', array['SeedsMafia']::text[], 'marketplace', 'ES', true, true),
  ('Alchimia Grow Shop', array['Alchimia']::text[], 'marketplace', 'ES', true, true),
  ('Cannapot', array['Canna Pot']::text[], 'marketplace', 'AT', true, true),
  ('Samenwahl', array['Samen Wahl']::text[], 'marketplace', 'DE', true, true),
  ('Seed City', array['Seed City Seeds']::text[], 'marketplace', 'UK', true, true),
  ('Sannies Seeds', array['Sannie Seeds']::text[], 'breeder', 'NL', true, true),
  ('Mandala Seeds', array['Mandala']::text[], 'breeder', 'ES', true, true),
  ('Afghan Selection', array['Afghan Selections']::text[], 'breeder', 'DK', true, true),
  ('Khalifa Genetics', array['Khalifa']::text[], 'breeder', 'FR', true, true),
  ('French Touch Seeds', array['French Touch']::text[], 'breeder', 'FR', true, true),
  ('Perfect Tree Seeds', array['Perfect Tree']::text[], 'breeder', 'ES', true, true),
  ('Silent Seeds', array['Silent']::text[], 'breeder', 'ES', true, true),
  ('Tropical Seeds Company', array['Tropical Seeds']::text[], 'breeder', 'ES', true, true),
  ('Biohazard Seeds', array['Biohazard']::text[], 'breeder', 'ES', true, true),
  ('Bulk Seed Bank', array['Bulk Seeds']::text[], 'seed_bank', 'ES', true, true),
  ('Soma Seeds', array['Soma']::text[], 'breeder', 'NL', true, true),
  ('Auto Seeds', array['AutoSeeds']::text[], 'autoflower_breeder', 'UK', true, true),
  ('Short Stuff Seeds', array['Short Stuff']::text[], 'autoflower_breeder', 'UK', true, true),
  ('Super Sativa Seed Club', array['SSSC']::text[], 'legacy_breeder', 'NL', true, true),
  ('Mandala Genetics', array['Mandala Genetics']::text[], 'breeder', 'ES', false, true),
  ('Autoflower Portal', array['Autoflower Portal Seeds']::text[], 'autoflower_breeder', 'US', false, true),
  ('Gnome Automatics', array['Gnome Auto', 'Gnome Genetics']::text[], 'autoflower_breeder', 'US', true, true),
  ('RocBud Inc.', array['RocBud', 'Roc Bud']::text[], 'autoflower_breeder', 'US', true, true),
  ('Twisted Tree Autoflowers', array['Twisted Tree']::text[], 'autoflower_breeder', 'US', true, true),
  ('Binary Selections', array['Binary Selections']::text[], 'autoflower_breeder', 'US', true, true),
  ('Magic Strains', array['Magic Strains Auto']::text[], 'autoflower_breeder', 'US', false, true),
  ('Mandalorian Genetics', array['Mandalorian']::text[], 'autoflower_breeder', 'US', true, true),
  ('Chef Anna White Label', array['Chef Anna']::text[], 'autoflower_breeder', 'US', false, true),
  ('Jean-O''s Genetics', array['Jean Os Genetics', 'Jean-O Genetics']::text[], 'autoflower_breeder', 'US', true, true),
  ('Laughing Hyena Seeds', array['Laughing Hyena']::text[], 'autoflower_breeder', 'CA', true, true),
  ('Gas Reaper Genetics', array['Gas Reaper']::text[], 'autoflower_breeder', 'US', true, true),
  ('Mosca Negra', array['Mosca Negra Seeds']::text[], 'breeder', 'US', true, true),
  ('Twenty20 Autoflowers', array['Twenty20 Auto']::text[], 'autoflower_breeder', 'US', true, true),
  ('Dutch Passion Auto', array['Dutch Passion Autoflower']::text[], 'autoflower_breeder', 'NL', true, true),
  ('Royal Queen Seeds Auto', array['RQS Auto']::text[], 'autoflower_breeder', 'ES', true, true),
  ('Sweet Seeds Auto', array['Sweet Auto']::text[], 'autoflower_breeder', 'ES', true, true),
  ('Greenpoint Seeds', array['Greenpoint']::text[], 'breeder', 'US', true, true),
  ('Badgers Dank', array['Badgers Dank Genetics']::text[], 'breeder', 'US', false, true),
  ('Pisces Genetics', array['Pisces']::text[], 'breeder', 'US', true, true),
  ('AlphaKronik Genes', array['AlphaKronik']::text[], 'legacy_breeder', 'US', true, true),
  ('Katsu Seeds', array['Katsu']::text[], 'breeder', 'US', true, true),
  ('People Under The Stairs Genetics', array['PUTS Genetics']::text[], 'breeder', 'US', false, true),
  ('Irie Genetics', array['Irie']::text[], 'breeder', 'US', true, true),
  ('Duke Diamond Vault', array['Duke Diamond']::text[], 'breeder', 'US', true, true),
  ('Dominion Seed Company', array['Dominion Seeds']::text[], 'breeder', 'US', true, true),
  ('Lucky Dog Seed Co.', array['Lucky Dog Seeds', 'Lucky Dog']::text[], 'breeder', 'US', true, true),
  ('Skunk VA', array['SkunkVA']::text[], 'breeder', 'US', true, true),
  ('AK Bean Brains Seeds', array['AK Bean Brains Seeds']::text[], 'breeder', 'US', false, true),
  ('Coastal Seed Co.', array['Coastal Seeds']::text[], 'breeder', 'US', true, true),
  ('Equilibrium Genetics', array['Equilibrium']::text[], 'breeder', 'US', true, true),
  ('Hyp3rids', array['Hyp3rids Seeds']::text[], 'breeder', 'US', true, true),
  ('Cricket & Cicada Seeds', array['Cricket and Cicada']::text[], 'breeder', 'US', true, true),
  ('707 Genetics', array['707 Genetics']::text[], 'breeder', 'US', false, true),
  ('Aficionado Seed Bank', array['Aficionado']::text[], 'breeder', 'US', true, true),
  ('Rebel Grown', array['Rebel Grown Seeds']::text[], 'breeder', 'US', true, true),
  ('NorCal Farms Genetics', array['NorCal Farms']::text[], 'breeder', 'US', false, true),
  ('Seed Kompany', array['The Seed Kompany']::text[], 'breeder', 'US', true, true),
  ('Swami Organic Seed', array['Swami Seeds', 'Swami Organic Seeds']::text[], 'breeder', 'US', true, true),
  ('Kingdom Organic Seeds', array['Kingdom Organic']::text[], 'breeder', 'US', true, true),
  ('Aficionado French Connection', array['French Connection']::text[], 'breeder', 'US', true, true),
  ('Cult Classics Seeds', array['Cult Classics']::text[], 'breeder', 'US', true, true),
  ('Elite Clone Seed Company', array['Elite Clone Seeds']::text[], 'breeder', 'US', false, true),
  ('Terp Fi3nd Genetics', array['Terp Fiend Genetics', 'Terp Fi3nd']::text[], 'breeder', 'US', true, true),
  ('Doc D Seeds', array['Doc D']::text[], 'breeder', 'US', true, true),
  ('Dragons Flame Genetics', array['Dragon''s Flame Genetics', 'Dragons Flame']::text[], 'breeder', 'US', true, true),
  ('Baked Beanz', array['Baked Beans']::text[], 'breeder', 'US', true, true),
  ('Mycotek Genetics', array['Mycotek']::text[], 'breeder', 'US', true, true),
  ('Nerds Genetics', array['Nerds']::text[], 'breeder', 'US', false, true),
  ('Symbiotic Genetics', array['Symbiotic']::text[], 'breeder', 'US', true, true),
  ('Tiki Madman', array['Tiki Madman Genetics']::text[], 'breeder', 'US', true, true),
  ('Fresh Coast Seed Co.', array['Fresh Coast Seeds']::text[], 'breeder', 'US', true, true),
  ('Surfr Seeds', array['Surfr Genetics']::text[], 'breeder', 'US', true, true),
  ('Lit Farms Autoflower', array['Lit Farms Auto']::text[], 'autoflower_breeder', 'US', false, true),
  ('Pacific NW Roots', array['PNW Roots']::text[], 'breeder', 'US', true, true),
  ('Subcool Seeds', array['TGA Subcool', 'Subcool']::text[], 'legacy_breeder', 'US', true, true),
  ('TGA Genetics', array['TGA Subcool Seeds']::text[], 'legacy_breeder', 'US', true, true),
  ('DJ Short Seeds', array['DJ Short']::text[], 'legacy_breeder', 'US', true, true),
  ('Old World Genetics', array['Old World Genetics']::text[], 'legacy_breeder', 'US', true, true),
  ('Afropips', array['Afropips Seeds']::text[], 'legacy_breeder', 'UK', true, true),
  ('Reeferman Genetics', array['Reeferman Genetics']::text[], 'legacy_breeder', 'CA', true, true),
  ('SickMeds Seeds', array['SickMeds']::text[], 'breeder', 'UK', true, true),
  ('Holy Smoke Seeds', array['Holy Smoke']::text[], 'breeder', 'UK', true, true),
  ('Malawi Gold Seed Co.', array['Malawi Gold Seeds']::text[], 'breeder', 'UK', false, true),
  ('Gage Green Group', array['Gage Green Genetics', 'GGG']::text[], 'breeder', 'US', true, true),
  ('Loompa Farms', array['Loompa']::text[], 'breeder', 'US', true, true),
  ('ThugPug Genetics', array['Thug Pug Genetics', 'ThugPug']::text[], 'breeder', 'US', true, true),
  ('Kre8 Genetics', array['Kre8']::text[], 'breeder', 'US', false, true),
  ('Relic Seeds', array['Relic']::text[], 'breeder', 'US', true, true),
  ('Oni Seed Co.', array['Oni Seeds', 'Oni']::text[], 'breeder', 'US', true, true),
  ('The Plug Seedbank', array['Plug Seedbank']::text[], 'marketplace', 'UK', true, true),
  ('Pro Seeds', array['ProSeeds']::text[], 'marketplace', 'DE', true, true),
  ('CannaPot Seed Shop', array['CannaPot Seedshop']::text[], 'marketplace', 'AT', true, true),
  ('Holland Seeds', array['Holland Seed Bank']::text[], 'seed_bank', 'NL', false, true),
  ('Weedseedsexpress', array['Weed Seeds Express']::text[], 'seed_bank', 'NL', true, true),
  ('Amsterdam Marijuana Seeds', array['AMS']::text[], 'seed_bank', 'NL', true, true),
  ('Pacific Seed Company', array['Pacific Seed Co']::text[], 'seed_bank', 'US', false, true),
  ('Seed Supreme', array['SeedSupreme']::text[], 'marketplace', 'UK', true, true),
  ('Seeds66', array['Seeds 66']::text[], 'marketplace', 'DE', true, true),
  ('United Cannabis Seeds', array['United Cannabis Seed Bank']::text[], 'seed_bank', 'US', true, true),
  ('Blimburn Seeds', array['Blimburn']::text[], 'breeder', 'ES', true, true),
  ('Expert Seeds', array['Expert Seed Bank']::text[], 'breeder', 'UK', true, true),
  ('GeneSeeds', array['Gene Seeds']::text[], 'seed_bank', 'DE', false, true),
  ('CannaBioGen', array['Cannabiogen']::text[], 'breeder', 'ES', true, true),
  ('CBD Crew', array['CBD Crew Seeds']::text[], 'breeder', 'ES', true, true)
on conflict (normalized_name) do update
set
  aliases = (
    select array(
      select distinct alias_value
      from unnest(coalesce(public.source_directory.aliases, array[]::text[]) || coalesce(excluded.aliases, array[]::text[])) as alias_values(alias_value)
      where btrim(alias_value) <> ''
      order by alias_value
    )
  ),
  source_type = excluded.source_type,
  country = coalesce(excluded.country, public.source_directory.country),
  verified = public.source_directory.verified or excluded.verified,
  active = true,
  updated_at = now();

notify pgrst, 'reload schema';
